arb-dir: lib/core/l10n/translations
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-dir: lib/core/l10n
output-class: AppLocalizations
untranslated-messages-file: untranslated_messages.json
synthetic-package: false