class PageDescriptionsService {
  static final PageDescriptionsService _instance = PageDescriptionsService._internal();
  factory PageDescriptionsService() => _instance;
  PageDescriptionsService._internal();

  // Descrizioni delle pagine nazionali
  final Map<int, String> nationalDescriptions = {
    100: 'Indice Nazionale',
    101: 'Ultim\'ora',
    102: '24 ore non stop',
    103: 'Prima pagina',
    104: 'Oggi',
    120: 'Politica',
    140: 'Dall\' Italia',
    150: 'Dal mondo',
    160: 'Culture',
    190: 'Motori',
    200: 'Sport',
    201: 'Calcio',
    202: 'Serie A Risultati',
    203: 'Serie A Classifica',
    204: 'Serie A Prossimo Turno',
    205: 'Serie A Marcatori',
    206: 'Serie A Diretta',
    207: 'Serie A Best 11',
    208: 'Serie A Giudice Sportivo',
    209: 'Serie B',
    210: 'Serie B Classifica',
    211: 'Serie B Prossimo Turno',
    212: 'Serie B Marcatori',
    213: 'Serie B Diretta',
    214: 'Serie C',
    215: 'Serie C Classifica',
    229: 'Brevi Calcio',
    230: 'Calcio Atalanta',
    231: 'Calcio Bologna',
    232: 'Calcio Cagliari',
    233: 'Calcio Como',
    234: 'Calcio Cremonese',
    235: 'Calcio Fiorentina',
    236: 'Calcio Genoa',
    237: 'Calcio Hellas Verona',
    238: 'Calcio Inter',
    239: 'Calcio Juventus',
    240: 'Calcio Lazio',
    241: 'Calcio Lecce',
    242: 'Calcio Milan',
    243: 'Calcio Napoli',
    244: 'Calcio Parma',
    245: 'Calcio Pisa',
    246: 'Calcio Roma',
    247: 'Calcio Sassuolo',
    248: 'Calcio Torino',
    249: 'Calcio Udinese',
    250: 'Calcio Club Serie B',
    251: 'Calcio Serie D Girone A', 
    252: 'Calcio Serie D Girone B',
    253: 'Calcio Serie D Girone C',
    254: 'Calcio Serie D Girone D',
    255: 'Calcio Serie D Girone E',
    256: 'Calcio Serie D Girone F',
    257: 'Calcio Serie D Girone G',
    258: 'Calcio Serie D Girone H',
    259: 'Calcio Serie D Girone I',
    260: 'Altri Sport',
    288: 'Calcio Donne',
    295: 'Calcio Inglese',
    296: 'Calcio Tedesco',
    297: 'Calcio Francese',
    298: 'Calcio Spagnolo',
    299: 'Brevissime',
    300: 'Borsa Fondi - NON DISPONIBILE',
    400: 'Indice Pubblica Utilità',
    401: 'Almanacco',
    402: 'Il Sole e la Luna',
    403: 'Il Santo',
    404: 'Feste e Tradizioni',
    405: 'Che tempo fa',
    407: 'Il traffico',
    410: 'Accadde oggi',
    411: 'Taccuino',
    412: 'La frase del giorno',
    413: 'Giornata mondiale',
    414: 'Il libro',
    417: 'La ricetta di...',
    418: 'La rosa dei venti',
    419: 'Curiosità dal mondo',
    420: 'Per i cittadini',
    421: 'Notizie utili',
    422: 'Notizie utili 2',
    423: 'Notizie utili 3',
    424: 'Notizie utili 4',
    425: 'Numeri di emergenza',
    426: 'Io ci vado',
    427: 'Io ci vado Teatro',
    428: 'Io ci vado Cinema',
    429: 'Io ci vado Festival',
    430: 'Io ci vado Musei',
    431: 'Pillole di euForia',
    433: 'In viaggio',
    434: 'Viaggiare sicuri',
    435: 'Viaggiare sicuri 2',
    436: 'Viaggiare sicuri 3',
    437: 'Viaggiare sicuri 4',
    438: 'Viaggiare sicuri 5',
    439: 'Viaggiare sicuri 6',
    440: 'Viaggiare sicuri 7',
    441: 'Viaggiare sicuri 8',
    442: 'Viaggiare sicuri 9',
    443: 'Storia delle strade d\' Italia',
    444: 'Belpaese',
    445: 'Cos\'è il FAI',
    446: 'I beni del FAI',
    447: 'Touring Club Italiano',
    448: 'Touring Club Italiano 2',
    450: 'Ambiente',
    451: 'Energie Rinnovabili',
    452: 'Riduci Riusa Ricicla',
    453: 'Sostenibilità ambientale',
    454: 'Agenda Verde',
    455: 'Mobilità sostenibile',
    456: 'Lo sapevate che...',
    460: 'Io non rischio',
    461: 'Io non rischio 2',
    462: 'Io non rischio 3',
    463: 'Io non rischio 4',
    464: 'Emergenze',
    465: 'Lavoro',
    466: 'Gazzetta Ufficiale',
    467: 'Lavoro: Sicurezza',
    468: 'Agenzie per il lavoro',
    469: 'Lavoro: Formazione',
    470: 'Eventi per il lavoro',
    475: 'Scienza e Salute',
    476: 'In Salute',
    477: 'Alimentazione',
    478: 'Falsi Miti',
    479: 'Focus',
    481: 'CNR',
    483: 'INAF',
    500: 'Radio e TV',
    501: 'Guida TV',
    502: 'Guida TV Oggi RAI 1',
    503: 'Guida TV Oggi RAI 2',
    504: 'Guida TV Oggi RAI 3',
    505: 'Guida TV Domani RAI 1',
    506: 'Guida TV Domani RAI 2',
    507: 'Guida TV Domani RAI 3',
    508: 'Guida TV Canale 5',
    509: 'Guida TV Rete 4',
    510: 'Guida TV Italia 1',
    511: 'Guida TV La7',
    512: 'Guida TV TV8',
    513: 'Guida TV Nove',
    514: 'Guida TV Film oggi',
    515: 'Guida TV Prima serata',
    517: 'Guida TV Criptati per l\'estero ',
    518: 'Guida TV Rai Sport+HD',
    519: 'Guida TV Rai Sport',
    520: 'Guida TV Rai Movie',
    521: 'Guida TV Rai Premium',
    522: 'Guida TV Rai Yoyo',
    523: 'Guida TV Rai 4',
    524: 'Guida TV Rai Gulp',
    525: 'Guida TV Rai 5',
    526: 'Guida TV Rai Storia',
    527: 'Guida TV Rai Scuola',
    530: 'Auditel',
    531: 'Auditel Percentuali',
    532: 'Auditel Ascpoltatori',
    533: 'Auditel I più visti',
    535: 'Guida Radio',
    536: 'Guida Rai Radio1',
    537: 'Guida Rai Radio2',
    538: 'Guida Rai Radio3',
    539: 'Guida No name Radio',
    540: 'Guida Rai Radio Classica',
    541: 'Guida Rai Radio Kids',
    542: 'Guida Rai Radio Live',
    543: 'Guida Rai Techetè',
    544: 'Guida Rai Radio Tutta Italiana',
    545: 'Magazine',
    546: 'Magazine TV',
    547: 'Settimana in TV: I programmi',
    548: 'Settimana in TV: I programmi 2',
    549: 'Settimana in TV: I programmi 3',
    550: 'Settimana in TV: I programmi 4',
    551: 'Settimana in TV: La fiction ',
    552: 'Settimana in TV: La fiction 2',
    553: 'Settimana in TV: Film da non perdere',
    554: 'Settimana in TV: Classica in TV',
    555: 'Settimana in TV: Leggera in TV',
    556: 'Settimana in TV: Documentari',
    560: 'Cultura e Spettacolo',
    561: 'Libri',
    562: 'Libri: Le pagine da leggere',
    564: 'Libri: Lo scaffale',
    565: 'Libri: All\'ordine del giorno',
    567: 'Cinema',
    568: 'Cinema: Home video - Streaming',
    569: 'Cinema: I film più visti',
    570: 'Cinema: Film in sala - Commedia',
    571: 'Cinema: Film in sala - Drammatico',
    572: 'Cinema: Film in sala - Documentario',
    573: 'Cinema: Film in sala - Azione/Animazione',

    574: 'Cinema: Film in sala - Thriller/Horror',
    575: 'Cinema: Film in sala - Film in arrivo',
    576: 'Teatri',
    577: 'Teatri Stabili',
    578: 'Teatri Stabili 2',
    579: 'Teatri Stabili 3',
    580: 'Teatri Lirici',
    581: 'Teatri Lirici 2',
    582: 'Teatri Lirici 3',
    583: 'Concerti',
    590: 'Viva La Rai',
    594: 'Ragazzi',
    595: 'Eventi e mostre',
    606: 'Notizie da...',
    613: 'Viabilità',
    614: 'Viabilità S.S. e Raccordi Nord-ovest',
    615: 'Viabilità S.S. e Raccordi Nord-est',
    616: 'Viabilità S.S. e Raccordi Centro',
    617: 'Viabilità S.S. e Raccordi Sud',
    618: 'Viabilità S.S. e Raccordi Isole',
    619: 'Viabilità Autostrade Nord-ovest',
    620: 'Viabilità Autostrade Nord-est',
    621: 'Viabilità Autostrade Centro',
    622: 'Viabilità Autostrade Sud',
    623: 'Viabilità Autostrade Isole',
    624: 'Infomobilità',
    625: 'Infomobilità Codice della strada',
    626: 'Infomobilità Sicurezza Stradale',
    627: 'Infomobilità Mobilità Sostenibile',
    628: 'Infomobilità Curiosità',
    690: 'Lotto Estrazioni',
    693: 'Lotto Numeri ritardatari',
    695: '10 e lotto',
    696: 'Nuovo Superenalotto',
    700: 'Meteo',
    702: 'Meteo Alpi e Valpadana oggi',
    703: 'Meteo Alpi e Valpadana domani',
    704: 'Meteo Ligure e Tirrenico oggi',
    705: 'Meteo Ligure e Tirrenico domani',
    706: 'Meteo Adriatico e Ionico oggi',
    707: 'Meteo Adriatico e Ionico domani',
    708: 'Meteo Tirreno Meridionale e Isole oggi',
    709: 'Meteo Tirreno Meridionale e Isole domani',
    710: 'Meteo Prossimi giorni',
    711: 'Meteo Temperature Italia',
    712: 'Meteo Temperature Estero',
    713: 'Meteo Previsioni Aeroporti Nord - Centro',
    714: 'Meteo Previsioni Aeroporti Sud - Isole',
    715: 'Meteo Mari Situazione',
    716: 'Meteo Mari Previsioni',
    717: 'Meteo Mari Venti',
    719: 'Meteo Guardia Costiera',
    735: 'Rai per la sostenibilità: ESG',
    740: 'Rai informa',
    755: 'Canone TV',
    770: 'Accessibilità Non Udenti',
    780: 'Accessibilità Non vedenti',
    
  };

  // Descrizioni delle pagine regionali
  final Map<int, String> regionalDescriptions = {
    100: 'Indice Regionale',
    101: 'Ultim\'ora',
    102: '24 ore non stop',
    103: 'Prima pagina',
    104: 'Oggi',
    120: 'Politica',
    140: 'Dall\' Italia',
    150: 'Dal mondo',
    160: 'Culture',
    190: 'Motori',
    200: 'Sport',
    201: 'Calcio',
    202: 'Serie A Risultati',
    203: 'Serie A Classifica',
    204: 'Serie A Prossimo Turno',
    205: 'Serie A Marcatori',
    206: 'Serie A Diretta',
    207: 'Serie A Best 11',
    208: 'Serie A Giudice Sportivo',
    209: 'Serie B',
    210: 'Serie B Classifica',
    211: 'Serie B Prossimo Turno',
    212: 'Serie B Marcatori',
    213: 'Serie B Diretta',
    214: 'Serie C',
    215: 'Serie C Classifica',
    229: 'Brevi Calcio',
    230: 'Calcio Atalanta',
    231: 'Calcio Bologna',
    232: 'Calcio Cagliari',
    233: 'Calcio Como',
    234: 'Calcio Cremonese',
    235: 'Calcio Fiorentina',
    236: 'Calcio Genoa',
    237: 'Calcio Hellas Verona',
    238: 'Calcio Inter',
    239: 'Calcio Juventus',
    240: 'Calcio Lazio',
    241: 'Calcio Lecce',
    242: 'Calcio Milan',
    243: 'Calcio Napoli',
    244: 'Calcio Parma',
    245: 'Calcio Pisa',
    246: 'Calcio Roma',
    247: 'Calcio Sassuolo',
    248: 'Calcio Torino',
    249: 'Calcio Udinese',
    250: 'Calcio Club Serie B',
    251: 'Calcio Serie D Girone A', 
    252: 'Calcio Serie D Girone B',
    253: 'Calcio Serie D Girone C',
    254: 'Calcio Serie D Girone D',
    255: 'Calcio Serie D Girone E',
    256: 'Calcio Serie D Girone F',
    257: 'Calcio Serie D Girone G',
    258: 'Calcio Serie D Girone H',
    259: 'Calcio Serie D Girone I',
    260: 'Altri Sport',
    288: 'Calcio Donne',
    295: 'Calcio Inglese',
    296: 'Calcio Tedesco',
    297: 'Calcio Francese',
    298: 'Calcio Spagnolo',
    299: 'Brevissime',
    //Pagine regionali
    300: 'Indice Regione',
    301: 'Sport Regione',
    302: 'Calcio Regione',
    307: 'Basket Regione',
    412: 'La regione del gusto',
  
  };

  // Descrizioni ARD Text (Germania)
  final Map<int, String> ardDescriptions = {
    100: 'Inhalt (Indice)',
    101: 'tagesschau: Nachrichten',
    102: 'Weitere Schlagzeilen',
    103: 'Nachrichten',
    104: 'Wetter',
    120: 'Heute im Bundestag',
    130: 'Wirtschaft',
    135: 'Aus aller Welt',
    140: 'Politik',
    145: 'Ausland',
    150: 'Kommentare',
    160: 'Börse',
    170: 'Sport',
    200: 'Sport',
    201: 'Fußball',
    202: 'Bundesliga',
    203: '2. Bundesliga',
    204: 'DFB-Pokal',
    206: 'Champions League',
    207: 'Europa League',
    208: 'Formel 1',
    209: 'Tennis',
    210: 'Wintersport',
    220: 'Weitere Sportarten',
    300: 'Programm',
    301: 'Das Erste - Programm heute',
    302: 'Das Erste - Programm morgen',
    303: 'Das Erste - Programm 20:15',
    304: 'Tagesschau24',
    305: 'ONE',
    306: 'ARD-alpha',
    307: 'Drittes Programm',
    308: 'Phoenix',
    309: 'KiKA',
    310: 'arte',
    311: 'Tagesthemen',
    312: '20 Uhr Tagesschau',
    320: 'ARD Mediathek',
    330: 'Audiodeskription',
    335: 'Untertitel',
    400: 'Kultur',
    401: 'Kulturkalender',
    402: 'Bühne',
    403: 'Ausstellungen',
    404: 'Musik',
    405: 'Literatur',
    406: 'Kino',
    407: 'Film im Fernsehen',
    410: 'Tatort',
    415: 'Medienpreise',
    420: 'Geschichte',
    500: 'Ratgeber',
    501: 'Gesundheit',
    502: 'Ernährung',
    503: 'Reise',
    504: 'Verkehr',
    505: 'Auto & Verkehr',
    506: 'Verbraucher',
    507: 'Recht',
    508: 'Familie',
    509: 'Bildung',
    510: 'Computer & Internet',
    520: 'Umwelt & Natur',
    530: 'Wissenschaft & Technik',
    600: 'Lotto',
    601: 'Lottozahlen Samstag',
    602: 'Lottozahlen Mittwoch',
    603: 'Eurojackpot',
    604: 'Glücksspirale',
    605: 'Keno',
    610: 'Horoskop',
    700: 'Börse',
    701: 'DAX',
    702: 'MDAX',
    703: 'TecDAX',
    704: 'SDAX',
    705: 'Dow Jones',
    706: 'Nasdaq',
    707: 'Euro Stoxx',
    708: 'Nikkei',
    709: 'Gold & Rohstoffe',
    710: 'Devisen',
    720: 'Unternehmen',
    730: 'Konjunktur',
    740: 'Börsen-News',
    750: 'Fonds',
    790: 'Service A-Z',
    791: 'Inhalt A-Z',
    800: 'Hörfunk',
    801: 'Programm Hörfunk heute',
    850: 'Impressum',
    880: 'Datenschutz',
    895: 'App & Neuheiten',
    899: 'Hinweise zur Bedienung',
  };

  // Descrizioni ZDF Text (Germania)
  final Map<int, String> zdfDescriptions = {
    100: 'Übersicht (Indice)',
    112: 'Nachrichten',
    113: 'Politik',
    114: 'Wirtschaft',
    115: 'Ausland',
    116: 'Panorama',
    117: 'Wissen',
    120: 'heute journal',
    121: 'heute',
    122: 'heute Xpress',
    130: 'Eilmeldungen',
    140: 'Inland',
    150: 'Kommentare',
    160: 'Börse',
    170: 'Wetter',
    171: 'Wetter Deutschland',
    172: 'Wetter Europa',
    173: 'Wetter Reiseziele',
    180: 'Verkehr',
    200: 'Sport',
    201: 'Fußball',
    202: 'Bundesliga',
    203: 'Bundesliga Tabelle',
    204: 'Bundesliga Torjäger',
    205: '2. Bundesliga',
    206: '2. Bundesliga Tabelle',
    207: 'DFB-Pokal',
    208: 'Champions League',
    209: 'Europa League',
    210: 'Formel 1',
    211: 'Tennis',
    212: 'Wintersport',
    213: 'Handball',
    214: 'Basketball',
    220: 'Weitere Sportarten',
    300: 'Programm',
    301: 'ZDF - heute',
    302: 'ZDF - morgen',
    303: 'ZDF - 20:15 Uhr',
    304: 'ZDFneo',
    305: 'ZDFinfo',
    306: '3sat',
    307: 'ARTE',
    308: 'Phoenix',
    309: 'KiKA',
    310: 'Drittes Programm',
    320: 'ZDF Mediathek',
    330: 'Untertitel',
    335: 'Audiodeskription',
    340: 'Gebärdensprache',
    400: 'Sport II',
    500: 'Kultur',
    501: 'Kulturkalender',
    502: 'Theater',
    503: 'Ausstellungen',
    504: 'Musik',
    505: 'Literatur',
    506: 'Kino',
    507: 'Film',
    510: 'aspekte',
    600: 'Ratgeber',
    601: 'Gesundheit',
    602: 'Ernährung',
    603: 'Reise',
    604: 'Verbraucher',
    605: 'Digital',
    606: 'Umwelt',
    607: 'Wissenschaft',
    700: 'Service',
    701: 'Lotto',
    702: 'Lottozahlen Samstag',
    703: 'Lottozahlen Mittwoch',
    704: 'Eurojackpot',
    705: 'Glücksspirale',
    706: 'Keno',
    710: 'Horoskop',
    720: 'TV-Tipps',
    800: 'Kontakt & Impressum',
    801: 'Kontakt',
    850: 'Impressum',
    880: 'Datenschutz',
    890: 'Barrierefreiheit',
    899: 'Hilfe',
  };

  // Descrizioni Swiss Teletext (Svizzera - RSI/RTS/SRF)
  final Map<int, String> swissDescriptions = {
    100: 'Indice / Sommaire / Übersicht',
    101: 'Notizie / Nouvelles / Nachrichten',
    102: 'Attualità / Actualité',
    103: 'Cronaca / Faits divers',
    120: 'Svizzera / Suisse / Schweiz',
    130: 'Ticino / Tessin',
    140: 'Romandia / Westschweiz',
    150: 'Mondo / Monde / Welt',
    200: 'Sport',
    201: 'Calcio / Football',
    202: 'Hockey',
    230: 'Sport Invernali',
    300: 'Programmi TV / Programmes TV',
    400: 'Cultura / Culture / Kultur',
    410: 'Cinema / Cinéma / Kino',
    420: 'Musica / Musique / Musik',
    500: 'Economia / Économie / Wirtschaft',
    520: 'Borsa / Bourse',
    600: 'Servizi / Services',
    610: 'Meteo / Météo / Wetter',
    700: 'Meteo / Météo / Wetter',
    750: 'Traffico / Trafic / Verkehr',
    800: 'Info Pratiche',
  };

  // Descrizioni ORF Teletext (Austria)
  final Map<int, String> orfDescriptions = {
    100: 'ORF Teletext Inhalt',
    101: 'Nachrichten',
    102: 'Weitere Meldungen',
    103: 'Österreich',
    104: 'International',
    105: 'Sport',
    106: 'Kultur',
    107: 'Wirtschaft',
    108: 'Chronik',
    109: 'Wetter',
    110: 'TV-Hinweise',
    116: 'Europa',
    120: 'Innenpolitik',
    130: 'Wirtschaft',
    140: 'Chronik Österreich',
    150: 'Ausland',
    200: 'Sport',
    201: 'Fußball',
    202: 'Bundesliga',
    203: 'Bundesliga Tabelle',
    230: 'Fußball International',
    240: 'Wintersport',
    250: 'Formel 1',
    260: 'Tennis',
    270: 'Sport Allgemein',
    300: 'ORF 1',
    310: 'ORF 2',
    320: 'ORF III',
    330: 'ORF Sport+',
    400: 'Service',
    450: 'Verkehr',
    460: 'Apotheken',
    500: 'Freizeit',
    520: 'Weltgeschehen',
    600: 'Wirtschaft',
    650: 'Gesundheit',
    680: 'ORF-Initiativen',
    700: 'Verkehr',
    750: 'Apotheken',
    800: 'Service A-Z',
    884: 'Offenlegung',
    885: 'Impressum',
  };

  // Descrizioni Spanish Teletext (Spagna - TVE, Antena 3, La Sexta)
  final Map<int, String> spanishDescriptions = {
    100: 'Índice',
    101: 'Noticias',
    102: 'España',
    103: 'Nacional',
    110: 'Primera Página',
    120: 'Internacional',
    130: 'Sociedad',
    135: 'Deportes',
    140: 'Cultura',
    150: 'Economía',
    159: 'El Tiempo',
    160: 'Sorteos',
    170: 'Servicios',
    180: 'La Bolsa',
    200: 'Deportes',
    201: 'Fútbol',
    202: 'Liga',
    203: 'Liga Clasificación',
    204: 'Liga Resultados',
    210: 'Quiniela',
    220: 'Baloncesto',
    230: 'Motor',
    250: 'La Vuelta',
    300: 'Servicios',
    301: 'Accesibilidad',
    330: 'Agenda Cultural',
    350: 'Libros',
    400: 'Programación TVE',
    430: 'El Cine en TVE',
    460: 'Loterías',
    600: 'Tráfico',
    700: 'El Tiempo',
    800: 'Subtítulos',
    879: 'Subtitulados',
    888: 'Gaceta Sordo',
  };

  // Descrizioni Portuguese Teletext (Portogallo - RTP)
  final Map<int, String> portugueseDescriptions = {
    100: 'Índice',
    102: 'Notícias',
    120: 'Internacional',
    121: 'Economia',
    150: 'Cultura',
    200: 'Desporto',
    201: 'Futebol',
    241: 'Bolsa',
    300: 'Televisão',
    301: 'Programação RTP',
    400: 'Desporto',
    420: 'Basquetebol',
    473: 'Campeonato Mundial',
    490: 'Totolotarias',
    491: 'Euromilhões',
    500: 'Utilidades',
    550: 'Saúde',
    575: 'Meteorologia',
    600: 'Trânsito',
    700: 'Tempo',
    800: 'Farmácias',
  };

  // Descrizioni Dutch Teletext (Olanda - NOS)
  final Map<int, String> dutchDescriptions = {
    100: 'Voorpagina',
    101: 'Nieuws',
    102: 'Economie',
    103: 'Binnenland',
    104: 'Buitenland',
    105: 'Politiek',
    106: 'Cultuur',
    110: 'Tech',
    120: 'Koningshuis',
    128: 'Europa',
    129: 'Internationaal',
    200: 'Televisie',
    201: 'TV Gids NPO1',
    202: 'TV Gids NPO2',
    203: 'TV Gids NPO3',
    250: 'Radio',
    501: 'Financieel',
    502: 'Beurs',
    600: 'Sport',
    601: 'Sport Nieuws',
    633: 'Voetbal',
    649: 'Tennis',
    678: 'Schaatsen',
    700: 'Weer',
    701: 'Verkeer',
    800: 'Voetbal',
    801: 'Eredivisie',
    803: 'Internationaal Voetbal',
    888: 'Ondertiteling',
  };

  // Descrizioni Swedish Teletext (Svezia - SVT)
  final Map<int, String> swedishDescriptions = {
    100: 'Nyheter',
    101: 'Inrikes',
    104: 'Utrikes',
    106: 'Ekonomi',
    110: 'Sport',
    130: 'Kultur',
    150: 'Hem och konsument',
    199: 'Senaste nytt',
    300: 'Sport',
    301: 'Sportnytt',
    302: 'Fotboll',
    330: 'Resultatbörsen',
    340: 'Ishockey',
    350: 'Vintersport',
    360: 'Motorsport',
    377: 'Målservice',
    400: 'Väder',
    401: 'Väder Sverige',
    410: 'Väderprognoser',
    500: 'Blandat',
    501: 'Resor',
    550: 'Djur och natur',
    600: 'På TV',
    601: 'SVT1',
    602: 'SVT2',
    610: 'TV-tips',
    700: 'Innehåll',
    701: 'Index',
    800: 'UR',
    801: 'Utbildning',
  };

  // Descrizioni Finnish Teletext (Finlandia - YLE)
  final Map<int, String> finnishDescriptions = {
    100: 'Uutiset',
    101: 'Uutisaiheet',
    160: 'Talous',
    190: 'English',
    199: 'Päähakemisto',
    201: 'Urheilu',
    202: 'Urheiluaiheet',
    300: 'Ohjelmat',
    301: 'TV-ohjelmat',
    350: 'Radiot',
    400: 'Sää',
    401: 'Sääennusteet',
    470: 'Veikkaus',
    500: 'Alueet',
    501: 'Uutiset alueelta',
    575: 'Teksti-TV',
    600: 'Yle Areena',
    700: 'Sisältö',
    799: 'Svenska',
    800: 'På svenska',
    890: 'Kalenteri',
    891: 'Aurinko',
    895: 'Ajatus päivälle',
  };

  // Descrizioni Slovenian Teletext (Slovenia - RTV SLO)
  final Map<int, String> slovenianDescriptions = {
    100: 'Indeks',
    101: 'Zadnja novica',
    102: 'Novice dneva',
    106: 'Wydarzenia dnia',
    110: 'Slovenija',
    111: 'Slovenija - Politika',
    113: 'Slovenija - Gospodarstvo',
    117: 'Slovenija - Družba',
    140: 'Svet',
    141: 'Svet - Politika',
    142: 'Svet - Gospodarstvo',
    160: 'Vreme',
    161: 'Vreme - Na kratko',
    162: 'Vreme - Slovenija',
    164: 'Vreme - Svet',
    165: 'Vreme - Letalstvo',
    166: 'Vreme - Agro',
    167: 'Vreme - Zrak',
    168: 'Vreme - Vode',
    169: 'Vreme - Pomorstvo',
    190: 'Črna kronika',
    200: 'TV program',
    300: 'Radio program',
    380: 'Slovenska smučišča',
    400: 'Kultura',
    500: 'Šport',
    505: 'Šport - Tabele',
    510: 'Nogomet',
    520: 'Hokej',
    531: 'Košarka',
    540: 'Rokomet',
    600: 'Zabava',
    610: 'Šale',
    700: 'Ostalo',
    710: 'Gospodarstvo',
    720: 'Promet',
    730: 'Loterija',
    740: 'Rekreacija',
    750: 'RKS',
    760: 'MMC uredništvo',
  };

  // Descrizioni Hungarian Teletext (Ungheria - MTVA)
  final Map<int, String> hungarianDescriptions = {
    100: 'Főmenü',
    101: 'Hírek',
    102: 'Belföld',
    103: 'Belföldi hírek',
    130: 'Külföld',
    131: 'Nemzetközi hírek',
    150: 'Gazdaság',
    151: 'Gazdasági hírek',
    160: 'Kultúra',
    161: 'Kulturális hírek',
    175: 'Tudomány',
    179: 'Vallás',
    200: 'Sport',
    201: 'Sport hírek',
    202: 'Foci',
    300: 'Időjárás',
    301: 'Időjárás előrejelzés',
    398: 'Légi közlekedés',
    470: 'Tőzsde',
    500: 'TV műsor',
    501: 'MTV1',
    502: 'MTV2',
    503: 'Duna TV',
    530: 'Rádió műsor',
    580: 'Közlekedés',
    700: 'Közérdekű információk',
    850: 'Közlekedési információk',
    861: 'Vízállás',
    898: 'Teletext információk',
  };

  // Descrizioni Icelandic Teletext (Islanda - RÚV)
  final Map<int, String> icelandicDescriptions = {
    100: 'Forsíða',
    101: 'Fréttir',
    102: 'Innlendar fréttir',
    103: 'Erlendar fréttir',
    104: 'Innlendar fréttir',
    105: 'Innlendar fréttir',
    120: 'Erlendar fréttir',
    121: 'Erlendar fréttir',
    140: 'Landsbyggðin',
    160: 'Veður',
    163: 'Landið',
    164: 'Næstu dagar',
    169: 'Weather forecast',
    181: 'Sjóveðurspá',
    200: 'Dagskrá',
    202: 'RÚV í kvöld',
    281: 'Lottó',
    300: 'Íþróttir',
    302: 'Íþróttafréttir',
    322: 'Laxveiðin',
    390: 'Boltaúrslit',
    400: 'Samgöngur',
    555: 'Efnisyfirlit A-Ö',
  };

  /// Ottiene le descrizioni in base al channelId
  Map<int, String> getDescriptionsForChannel({
    required String? channelId,
    required bool isRegional,
  }) {
    // Se channelId è null o inizia con 'rai', usa le descrizioni RAI
    if (channelId == null || channelId.startsWith('rai')) {
      return isRegional ? regionalDescriptions : nationalDescriptions;
    }
    
    // ARD Text
    if (channelId == 'ard_text') {
      return ardDescriptions;
    }
    
    // ZDF Text (tutti i canali ZDF usano le stesse descrizioni base)
    if (channelId == 'zdf_text' || 
        channelId == 'zdfinfo_text' || 
        channelId == 'zdfneo_text' || 
        channelId == '3sat_text') {
      return zdfDescriptions;
    }
    
    // Swiss Teletext (RSI, RTS, SRF)
    if (channelId.startsWith('rsi_') || 
        channelId.startsWith('rts_') || 
        channelId.startsWith('srf_')) {
      return swissDescriptions;
    }
    
    // ORF Teletext (Austria)
    if (channelId == 'orf1' || 
        channelId == 'orf2' || 
        channelId == 'orf3' || 
        channelId == 'orf_sport_plus') {
      return orfDescriptions;
    }
    
    // Spanish Teletext (Spagna)
    if (channelId == 'tve' || 
        channelId == 'antena3' || 
        channelId == 'lasexta') {
      return spanishDescriptions;
    }
    
    // Portuguese Teletext (Portogallo)
    if (channelId == 'rtp') {
      return portugueseDescriptions;
    }
    
    // Dutch Teletext (Olanda)
    if (channelId == 'nos_teletekst') {
      return dutchDescriptions;
    }
    
    // Swedish Teletext (Svezia)
    if (channelId == 'svt_text') {
      return swedishDescriptions;
    }
    
    // Finnish Teletext (Finlandia)
    if (channelId == 'yle_teksti_tv') {
      return finnishDescriptions;
    }
    
    // Slovenian Teletext (Slovenia)
    if (channelId == 'rtvslo_teletext') {
      return slovenianDescriptions;
    }
    
    // Hungarian Teletext (Ungheria)
    if (channelId == 'mtva_teletext') {
      return hungarianDescriptions;
    }
    
    // Icelandic Teletext (Islanda)
    if (channelId == 'ruv_textavarp') {
      return icelandicDescriptions;
    }
    
    // Default: RAI nazionale
    return nationalDescriptions;
  }

  // Ottiene la descrizione di una pagina (metodo legacy)
  @Deprecated('Use getDescriptionsForChannel instead')
  String getDescription(int pageNumber, {bool isRegional = false}) {
    final descriptions = isRegional ? regionalDescriptions : nationalDescriptions;
    return descriptions[pageNumber] ?? 'Pagina $pageNumber';
  }
} 