class PageDescriptionsService {
  static final PageDescriptionsService _instance = PageDescriptionsService._internal();
  factory PageDescriptionsService() => _instance;
  PageDescriptionsService._internal();

  // Descrizioni delle pagine nazionali
  final Map<int, String> nationalDescriptions = {
    100: 'Indice Nazionale',
    101: 'Ultim\'ora',
    102: '24 ore non stop',
    103: 'Prima pagina',
    104: 'Oggi',
    120: 'Politica',
    140: 'Dall\' Italia',
    150: 'Dal mondo',
    160: 'Culture',
    190: 'Motori',
    200: 'Sport',
    201: 'Calcio',
    202: 'Serie A Risultati',
    203: 'Serie A Classifica',
    204: 'Serie A Prossimo Turno',
    205: 'Serie A Marcatori',
    206: 'Serie A Diretta',
    207: 'Serie A Best 11',
    208: 'Serie A Giudice Sportivo',
    209: 'Serie B',
    210: 'Serie B Classifica',
    211: 'Serie B Prossimo Turno',
    212: 'Serie B Marcatori',
    213: 'Serie B Diretta',
    214: 'Serie C',
    215: 'Serie C Classifica',
    229: 'Brevi Calcio',
    230: 'Calcio Atalanta',
    231: 'Calcio Bologna',
    232: 'Calcio Cagliari',
    233: 'Calcio Como',
    234: 'Calcio Cremonese',
    235: 'Calcio Fiorentina',
    236: 'Calcio Genoa',
    237: 'Calcio Hellas Verona',
    238: 'Calcio Inter',
    239: 'Calcio Juventus',
    240: 'Calcio Lazio',
    241: 'Calcio Lecce',
    242: 'Calcio Milan',
    243: 'Calcio Napoli',
    244: 'Calcio Parma',
    245: 'Calcio Pisa',
    246: 'Calcio Roma',
    247: 'Calcio Sassuolo',
    248: 'Calcio Torino',
    249: 'Calcio Udinese',
    250: 'Calcio Club Serie B',
    251: 'Calcio Serie D Girone A', 
    252: 'Calcio Serie D Girone B',
    253: 'Calcio Serie D Girone C',
    254: 'Calcio Serie D Girone D',
    255: 'Calcio Serie D Girone E',
    256: 'Calcio Serie D Girone F',
    257: 'Calcio Serie D Girone G',
    258: 'Calcio Serie D Girone H',
    259: 'Calcio Serie D Girone I',
    260: 'Altri Sport',
    288: 'Calcio Donne',
    295: 'Calcio Inglese',
    296: 'Calcio Tedesco',
    297: 'Calcio Francese',
    298: 'Calcio Spagnolo',
    299: 'Brevissime',
    300: 'Borsa Fondi - NON DISPONIBILE',
    400: 'Indice Pubblica Utilità',
    401: 'Almanacco',
    402: 'Il Sole e la Luna',
    403: 'Il Santo',
    404: 'Feste e Tradizioni',
    405: 'Che tempo fa',
    407: 'Il traffico',
    410: 'Accadde oggi',
    411: 'Taccuino',
    412: 'La frase del giorno',
    413: 'Giornata mondiale',
    414: 'Il libro',
    417: 'La ricetta di...',
    418: 'La rosa dei venti',
    419: 'Curiosità dal mondo',
    420: 'Per i cittadini',
    421: 'Notizie utili',
    422: 'Notizie utili 2',
    423: 'Notizie utili 3',
    424: 'Notizie utili 4',
    425: 'Numeri di emergenza',
    426: 'Io ci vado',
    427: 'Io ci vado Teatro',
    428: 'Io ci vado Cinema',
    429: 'Io ci vado Festival',
    430: 'Io ci vado Musei',
    431: 'Pillole di euForia',
    433: 'In viaggio',
    434: 'Viaggiare sicuri',
    435: 'Viaggiare sicuri 2',
    436: 'Viaggiare sicuri 3',
    437: 'Viaggiare sicuri 4',
    438: 'Viaggiare sicuri 5',
    439: 'Viaggiare sicuri 6',
    440: 'Viaggiare sicuri 7',
    441: 'Viaggiare sicuri 8',
    442: 'Viaggiare sicuri 9',
    443: 'Storia delle strade d\' Italia',
    444: 'Belpaese',
    445: 'Cos\'è il FAI',
    446: 'I beni del FAI',
    447: 'Touring Club Italiano',
    448: 'Touring Club Italiano 2',
    450: 'Ambiente',
    451: 'Energie Rinnovabili',
    452: 'Riduci Riusa Ricicla',
    453: 'Sostenibilità ambientale',
    454: 'Agenda Verde',
    455: 'Mobilità sostenibile',
    456: 'Lo sapevate che...',
    460: 'Io non rischio',
    461: 'Io non rischio 2',
    462: 'Io non rischio 3',
    463: 'Io non rischio 4',
    464: 'Emergenze',
    465: 'Lavoro',
    466: 'Gazzetta Ufficiale',
    467: 'Lavoro: Sicurezza',
    468: 'Agenzie per il lavoro',
    469: 'Lavoro: Formazione',
    470: 'Eventi per il lavoro',
    475: 'Scienza e Salute',
    476: 'In Salute',
    477: 'Alimentazione',
    478: 'Falsi Miti',
    479: 'Focus',
    481: 'CNR',
    483: 'INAF',
    500: 'Radio e TV',
    501: 'Guida TV',
    502: 'Guida TV Oggi RAI 1',
    503: 'Guida TV Oggi RAI 2',
    504: 'Guida TV Oggi RAI 3',
    505: 'Guida TV Domani RAI 1',
    506: 'Guida TV Domani RAI 2',
    507: 'Guida TV Domani RAI 3',
    508: 'Guida TV Canale 5',
    509: 'Guida TV Rete 4',
    510: 'Guida TV Italia 1',
    511: 'Guida TV La7',
    512: 'Guida TV TV8',
    513: 'Guida TV Nove',
    514: 'Guida TV Film oggi',
    515: 'Guida TV Prima serata',
    517: 'Guida TV Criptati per l\'estero ',
    518: 'Guida TV Rai Sport+HD',
    519: 'Guida TV Rai Sport',
    520: 'Guida TV Rai Movie',
    521: 'Guida TV Rai Premium',
    522: 'Guida TV Rai Yoyo',
    523: 'Guida TV Rai 4',
    524: 'Guida TV Rai Gulp',
    525: 'Guida TV Rai 5',
    526: 'Guida TV Rai Storia',
    527: 'Guida TV Rai Scuola',
    530: 'Auditel',
    531: 'Auditel Percentuali',
    532: 'Auditel Ascpoltatori',
    533: 'Auditel I più visti',
    535: 'Guida Radio',
    536: 'Guida Rai Radio1',
    537: 'Guida Rai Radio2',
    538: 'Guida Rai Radio3',
    539: 'Guida No name Radio',
    540: 'Guida Rai Radio Classica',
    541: 'Guida Rai Radio Kids',
    542: 'Guida Rai Radio Live',
    543: 'Guida Rai Techetè',
    544: 'Guida Rai Radio Tutta Italiana',
    545: 'Magazine',
    546: 'Magazine TV',
    547: 'Settimana in TV: I programmi',
    548: 'Settimana in TV: I programmi 2',
    549: 'Settimana in TV: I programmi 3',
    550: 'Settimana in TV: I programmi 4',
    551: 'Settimana in TV: La fiction ',
    552: 'Settimana in TV: La fiction 2',
    553: 'Settimana in TV: Film da non perdere',
    554: 'Settimana in TV: Classica in TV',
    555: 'Settimana in TV: Leggera in TV',
    556: 'Settimana in TV: Documentari',
    560: 'Cultura e Spettacolo',
    561: 'Libri',
    562: 'Libri: Le pagine da leggere',
    564: 'Libri: Lo scaffale',
    565: 'Libri: All\'ordine del giorno',
    567: 'Cinema',
    568: 'Cinema: Home video - Streaming',
    569: 'Cinema: I film più visti',
    570: 'Cinema: Film in sala - Commedia',
    571: 'Cinema: Film in sala - Drammatico',
    572: 'Cinema: Film in sala - Documentario',
    573: 'Cinema: Film in sala - Azione/Animazione',

    574: 'Cinema: Film in sala - Thriller/Horror',
    575: 'Cinema: Film in sala - Film in arrivo',
    576: 'Teatri',
    577: 'Teatri Stabili',
    578: 'Teatri Stabili 2',
    579: 'Teatri Stabili 3',
    580: 'Teatri Lirici',
    581: 'Teatri Lirici 2',
    582: 'Teatri Lirici 3',
    583: 'Concerti',
    590: 'Viva La Rai',
    594: 'Ragazzi',
    595: 'Eventi e mostre',
    606: 'Notizie da...',
    613: 'Viabilità',
    614: 'Viabilità S.S. e Raccordi Nord-ovest',
    615: 'Viabilità S.S. e Raccordi Nord-est',
    616: 'Viabilità S.S. e Raccordi Centro',
    617: 'Viabilità S.S. e Raccordi Sud',
    618: 'Viabilità S.S. e Raccordi Isole',
    619: 'Viabilità Autostrade Nord-ovest',
    620: 'Viabilità Autostrade Nord-est',
    621: 'Viabilità Autostrade Centro',
    622: 'Viabilità Autostrade Sud',
    623: 'Viabilità Autostrade Isole',
    624: 'Infomobilità',
    625: 'Infomobilità Codice della strada',
    626: 'Infomobilità Sicurezza Stradale',
    627: 'Infomobilità Mobilità Sostenibile',
    628: 'Infomobilità Curiosità',
    690: 'Lotto Estrazioni',
    693: 'Lotto Numeri ritardatari',
    695: '10 e lotto',
    696: 'Nuovo Superenalotto',
    700: 'Meteo',
    702: 'Meteo Alpi e Valpadana oggi',
    703: 'Meteo Alpi e Valpadana domani',
    704: 'Meteo Ligure e Tirrenico oggi',
    705: 'Meteo Ligure e Tirrenico domani',
    706: 'Meteo Adriatico e Ionico oggi',
    707: 'Meteo Adriatico e Ionico domani',
    708: 'Meteo Tirreno Meridionale e Isole oggi',
    709: 'Meteo Tirreno Meridionale e Isole domani',
    710: 'Meteo Prossimi giorni',
    711: 'Meteo Temperature Italia',
    712: 'Meteo Temperature Estero',
    713: 'Meteo Previsioni Aeroporti Nord - Centro',
    714: 'Meteo Previsioni Aeroporti Sud - Isole',
    715: 'Meteo Mari Situazione',
    716: 'Meteo Mari Previsioni',
    717: 'Meteo Mari Venti',
    719: 'Meteo Guardia Costiera',
    735: 'Rai per la sostenibilità: ESG',
    740: 'Rai informa',
    755: 'Canone TV',
    770: 'Accessibilità Non Udenti',
    780: 'Accessibilità Non vedenti',
    
  };

  // Descrizioni delle pagine regionali
  final Map<int, String> regionalDescriptions = {
    100: 'Indice Regionale',
    101: 'Ultim\'ora',
    102: '24 ore non stop',
    103: 'Prima pagina',
    104: 'Oggi',
    120: 'Politica',
    140: 'Dall\' Italia',
    150: 'Dal mondo',
    160: 'Culture',
    190: 'Motori',
    200: 'Sport',
    201: 'Calcio',
    202: 'Serie A Risultati',
    203: 'Serie A Classifica',
    204: 'Serie A Prossimo Turno',
    205: 'Serie A Marcatori',
    206: 'Serie A Diretta',
    207: 'Serie A Best 11',
    208: 'Serie A Giudice Sportivo',
    209: 'Serie B',
    210: 'Serie B Classifica',
    211: 'Serie B Prossimo Turno',
    212: 'Serie B Marcatori',
    213: 'Serie B Diretta',
    214: 'Serie C',
    215: 'Serie C Classifica',
    229: 'Brevi Calcio',
    230: 'Calcio Atalanta',
    231: 'Calcio Bologna',
    232: 'Calcio Cagliari',
    233: 'Calcio Como',
    234: 'Calcio Cremonese',
    235: 'Calcio Fiorentina',
    236: 'Calcio Genoa',
    237: 'Calcio Hellas Verona',
    238: 'Calcio Inter',
    239: 'Calcio Juventus',
    240: 'Calcio Lazio',
    241: 'Calcio Lecce',
    242: 'Calcio Milan',
    243: 'Calcio Napoli',
    244: 'Calcio Parma',
    245: 'Calcio Pisa',
    246: 'Calcio Roma',
    247: 'Calcio Sassuolo',
    248: 'Calcio Torino',
    249: 'Calcio Udinese',
    250: 'Calcio Club Serie B',
    251: 'Calcio Serie D Girone A', 
    252: 'Calcio Serie D Girone B',
    253: 'Calcio Serie D Girone C',
    254: 'Calcio Serie D Girone D',
    255: 'Calcio Serie D Girone E',
    256: 'Calcio Serie D Girone F',
    257: 'Calcio Serie D Girone G',
    258: 'Calcio Serie D Girone H',
    259: 'Calcio Serie D Girone I',
    260: 'Altri Sport',
    288: 'Calcio Donne',
    295: 'Calcio Inglese',
    296: 'Calcio Tedesco',
    297: 'Calcio Francese',
    298: 'Calcio Spagnolo',
    299: 'Brevissime',
    //Pagine regionali
    300: 'Indice Regione',
    301: 'Sport Regione',
    302: 'Calcio Regione',
    307: 'Basket Regione',
    412: 'La regione del gusto',
  
  };

  // Descrizioni ARD Text (Germania)
  final Map<int, String> ardDescriptions = {
    100: 'Übersicht',
    101: 'tagesschau / Nachrichten / Politik',
    130: 'DeutschlandTrend',
    135: 'Aus aller Welt',
    145: 'Wissen / Umwelt',
    150: 'Untertitel (UT) - Einschalten',
    155: 'Wirtschaft',
    165: 'Verbraucher',
    168: 'Neu ab',
    170: 'Wetter',
    176: 'Temperaturen',
    178: 'Unwetterwarnung',
    180: 'Pollenflug',
    183: 'UV-Index',
    200: 'Sport I',
    249: 'Letzte Seite - Sport',
    250: 'Fußball / Bundesligen Fußball',
    275: 'Fußball 2.BL',
    300: 'Programm / Das Erste / Fernsehen',
    333: 'Zurzeit im TV',
    360: 'Wochenvorschau',
    369: 'Märchenfilme',
    370: 'ARD-Sendungen',
    388: 'Tatort / Polizeiruf: Filmmusik aktuelle Folge',
    397: 'Audiodeskription / Hörfilme',
    398: 'Gebärdensprache / Untertitel (UT) - Infos',
    399: 'Neu im Programm',
    400: 'Kultur',
    401: 'Kalenderblatt',
    402: 'Sonne / Mond',
    403: 'Geburtstage',
    404: 'Todestage',
    405: 'Geschichte',
    406: 'Gedenktage / Feiertage',
    408: 'Kirche',
    409: 'Kirche',
    410: 'Kultur',
    420: 'Leute / Promi-News',
    430: 'Medien',
    440: 'ARD-Adressen',
    441: 'ARD-Zuschauerredaktion / Zuschauerredaktion',
    442: 'Ticket-Service',
    444: 'Einschaltquoten / GfK-Zahlen / Marktanteile TV',
    450: 'Programm / Neues Das Erste',
    480: 'Deutschlandradio / Hörfunk',
    489: 'Deutsche Welle',
    500: 'Sport II / Fußball',
    501: 'Fußball 3.Liga',
    508: 'Fußball Frauen',
    510: 'Fußball RL / Regionalligen',
    520: 'Fußball Ausland / Auslandsligen',
    550: 'Fußball Pokale',
    580: 'Gewinnzahlen / Lotto',
    584: 'Auswahlwette / Toto',
    585: 'Klassenlotterie / NKL',
    586: 'SKL',
    587: 'Glücksspirale',
    588: 'Fernsehlotterie',
    595: 'Tor des Monats',
    599: 'Weltzeituhr',
    600: 'Sport III',
    650: 'Fußball / Basketball / Bundesligen Sport / Eishockey Ligen / Handball Ligen / Hockey Ligen / Tischtennis / Volleyball',
    690: 'Basketball NBA / Football NFL / US-Sport',
    699: 'Torticker',
    700: 'Börse / Marktberichte',
    701: 'Marktberichte',
    710: 'Aktienkurse / Börsenkurse',
    711: 'Indizes',
    712: 'Indizes',
    713: 'Devisen / Goldkurse',
    714: 'Devisen / Sortenkurse',
    715: 'DAX Stuttgart',
    716: 'MDAX Stuttgart',
    717: 'TecDAX Stuttgart',
    718: 'SDAX Stuttgart',
    720: 'Dow Jones 30',
    721: 'Nasdaq 100',
    724: 'DAX-Ticker',
    725: 'Fonds / Investmentfonds',
    770: 'Wir über uns',
    776: 'Karaoke / Liedtexte',
    778: 'ARD Text HbbTV / mobil',
    779: 'Kunst-Aktionen',
    783: 'Frequenzen',
    784: 'Frequenzen',
    791: 'Inhalt A-Z',
    792: 'Inhalt A-Z',
    793: 'Inhalt A-Z',
    794: 'Inhalt A-Z',
    795: 'Inhalt A-Z',
    796: 'Inhalt A-Z',
    797: 'Impressum / Zuschauertelefon',
    798: 'Rundfunkbeitrag',
    800: 'ARD Text Extra / Extra im Text / Themenseiten',
    870: 'Nachrichtenleicht',
    888: 'Spendenkonten',
    889: 'Aktuelle Hinweise / In eigener Sache / Störung',
    899: 'Letzte Seite',
  };

  // Descrizioni ZDF Text (Germania - ZDF Hauptprogramm)
  final Map<int, String> zdfDescriptions = {
    100: 'Übersicht (Indice)',
    109: 'Impressum / ZDFtext Kontakt',
    111: 'Schlagzeilen',
    112: 'Nachrichten / Politik',
    170: 'Wetter',
    171: 'Wetter Deutschland',
    179: 'Pollenflug',
    180: 'UV-Index',
    181: 'Europawetter / Wetter Europa',
    182: 'Weltwetter',
    183: 'Schneehöhen',
    200: 'Sport',
    204: 'Champions League / Fußball-Europapokal',
    230: 'Fußball-Europa League / Frauenfußball',
    250: 'Fußball',
    251: 'Fußball-Bundesliga',
    287: 'Fußball-Dritte Liga',
    290: 'Fußball-Regionalligen',
    296: 'Fußball-DFB-Pokal',
    300: 'Programm',
    301: 'Programm Heute',
    333: 'Jetzt im ZDF',
    350: 'Programm Morgen',
    400: 'Basketball / Eishockey / Handball / Volleyball',
    414: 'Tischtennis',
    416: 'Hockey',
    418: 'Badminton',
    419: 'Triathlon',
    420: 'US-Sport',
    425: 'Football',
    427: 'Radsport',
    430: 'Tennis',
    438: 'Davis Cup / Fed Cup',
    439: 'Golf',
    444: 'Einschaltquoten / GfK / Quoten',
    450: 'Fußball-Auslandsligen',
    551: 'Gottesdienst',
    555: 'Gewinnzahlen',
    556: 'Lotto Samstag',
    557: 'Lotto Mittwoch',
    558: 'Auswahlwette / Ergebniswette / Toto',
    559: 'Glücksspirale',
    560: 'Aktion Mensch',
    561: 'NKL',
    562: 'SKL',
    701: 'ZDF-Anschrift / E-Mail / Faxnummer / Zuschauerelefon',
    707: 'Aktenzeichen XY',
    710: 'ZDFinfo',
    715: 'ZDFneo',
    724: 'Klare Sprache',
    725: 'Empfang / Satellitenfrequenzen',
    727: 'DVB-Untertitel',
    728: 'HbbTV',
    729: 'DVB-T',
    730: 'Programm Wochenvorschau',
    738: 'Rundfunkbeitrag',
    739: 'Grundnetzsender',
    740: 'Deutschlandradio',
    746: 'Deutsche Welle',
    747: 'Spielfilme',
    748: 'Hörfilme',
    749: 'UT-Vorschau',
    750: 'Formel 1 / Fußball-EM',
    770: 'Biathlon / Wintersport',
    775: 'Skispringen',
    777: 'Untertitel (UT)',
    780: 'Ski Alpin',
    790: 'Eisschnelllauf',
    890: 'Spendenkonten',
  };

  // Descrizioni ZDFinfo Text (Germania - Canale documentaristico)
  final Map<int, String> zdfinfoDescriptions = {
    100: 'Übersicht',
    101: 'Inhalt',
    109: 'Impressum',
    112: 'Nachrichten / Politik',
    179: 'Pollenflug',
    181: 'Europawetter',
    183: 'Schneehöhen',
    199: 'Testseite',
    300: 'Programm',
    301: 'Programm Heute',
    333: 'Jetzt in ZDFinfo',
    350: 'Programm Morgen',
    444: 'Einschaltquoten / Quoten',
    555: 'Gewinnzahlen Übersicht',
    556: 'Lotto am Samstag',
    557: 'Lotto am Mittwoch',
    558: 'Toto: Auswahlwette / Ergebniswette',
    559: 'Glücksspirale',
    560: 'Aktion Mensch',
    561: 'NKL',
    562: 'SKL',
    710: 'ZDF-Programm',
    715: 'ZDFneo',
    725: 'Empfang / Satellitenfrequenzen',
    728: 'HbbTV',
    729: 'DVB-T',
    730: 'Programm Wochenvorschau',
    738: 'Rundfunkbeitrag',
    800: 'Magazin Übersicht',
    890: 'Spendenkonten',
  };

  // Descrizioni ZDFneo Text (Germania - Canale giovane/entertainment)
  final Map<int, String> zdfneoDescriptions = {
    100: 'Übersicht',
    101: 'Inhalt',
    109: 'Impressum',
    112: 'Nachrichten / Politik / Schlagzeilen',
    170: 'Wetter',
    171: 'Wetter Deutschland',
    179: 'Pollenflug',
    180: 'UV-Index',
    181: 'Europawetter / Wetter Europa',
    182: 'Wetter International',
    183: 'Schneehöhen',
    199: 'Testseite',
    300: 'Programm',
    301: 'Programm Heute',
    333: 'Jetzt in ZDFneo',
    350: 'Programm Morgen',
    444: 'Einschaltquoten / Quoten',
    500: 'Service',
    555: 'Gewinnzahlen Übersicht',
    556: 'Lotto am Samstag',
    557: 'Lotto am Mittwoch',
    558: 'Toto: Auswahlwette',
    559: 'Toto: Ergebniswette / Glücksspirale',
    560: 'Aktion Mensch',
    561: 'NKL',
    562: 'SKL',
    700: 'TV-Service',
    710: 'ZDFinfo',
    715: 'ZDF-Programm',
    725: 'Empfang',
    728: 'HbbTV',
    729: 'DVB-T',
    730: 'Programm Wochenvorschau',
    738: 'Rundfunkbeitrag',
    800: 'Magazin Übersicht',
    890: 'Spendenkonten',
  };

  // Descrizioni 3sat Text (Germania/Austria/Svizzera - Canale culturale)
  final Map<int, String> dreisatDescriptions = {
    100: 'Übersicht',
    108: 'Nutzerhinweise',
    110: 'Zuschauerservice',
    112: 'Nachrichten Deutschland',
    150: 'Nachrichten Österreich',
    151: 'Nachrichten Schweiz',
    200: 'Sport',
    283: 'Toto Deutschland',
    285: 'Toto Österreich',
    301: 'TV heute',
    305: 'Sendungen / TV-Tipps heute',
    333: 'Jetzt im Programm',
    334: 'TV morgen',
    350: 'TV-Tipps morgen',
    390: 'TV Woche',
    401: 'Wetter',
    403: 'Prognose (Wetter) Deutschland',
    404: 'Prognose (Wetter) Österreich',
    406: 'Prognose (Wetter) Schweiz',
    420: 'Schneehöhen',
    424: 'Pistenbericht Schweiz',
    437: 'Rodelbericht Schweiz',
    525: 'Theater',
    670: 'Symbole / Zeichenerklärung / Zweikanalton',
    672: 'Sendemitschnitt',
    700: 'Service / Unterhaltung',
    706: 'Schach',
    775: 'Untertitel: Information zum Empfang',
    776: 'Untertitel Vorschau',
    777: 'Untertitel VT-Einblendung',
    898: 'Zeichenvorrat',
    899: 'Testseite',
  };

  // Descrizioni RSI Teletext (Svizzera italiana - RSI LA1 e LA2)
  final Map<int, String> rsiDescriptions = {
    100: 'News',
    104: 'Svizzera',
    125: 'Ticino & Grigioni',
    145: 'Estero',
    165: 'Economia',
    175: 'Cultura',
    180: 'Sport / Notizie',
    200: 'Sport Indice',
    201: 'Calcio svizzero',
    230: 'Calcio internazionale',
    260: 'Calcio coppe europee',
    280: 'Calcio CE',
    300: 'Hockey svizzero',
    320: 'Hockey internazionale',
    330: 'Tennis',
    350: 'Ciclismo',
    370: 'F1+Moto',
    380: 'Basket/Volley',
    500: 'Meteo',
    501: 'Previsioni',
    510: 'Speciale Meteo',
    700: 'TV & Radio',
    702: 'Programmi di oggi',
    706: 'Programmi di domani',
    712: 'I film su LA 1',
    720: 'Trasmissioni',
    770: 'Sottotitoli',
    800: 'Impressum',
    891: 'Impressum',
    893: 'Index A-Z',
  };

  // Descrizioni RTS Teletext (Svizzera francese - RTS 1 e 2)
  final Map<int, String> rtsDescriptions = {
    100: 'News',
    104: 'Suisse',
    130: 'Etranger',
    150: 'Economie',
    165: 'Culture',
    180: 'Sport / News',
    200: 'Sport Index',
    201: 'Football suisse',
    230: 'Football championnats étrangers',
    260: 'Football CL & EL',
    280: 'Football CE',
    300: 'Hockey suisse',
    320: 'Hockey international',
    330: 'Tennis',
    360: 'Cyclisme',
    370: 'F1+Moto',
    380: 'Basket/Volley',
    500: 'Météo',
    501: 'Prévisions',
    510: 'Météo-Spécial',
    700: 'TV & Radio',
    702: 'Programme TV aujourd\'hui',
    712: 'Programme TV Un demain',
    717: 'Sport à la RTS',
    735: 'Emissions RTS',
    770: 'Sous-titrage',
    780: 'Radios RTS',
    800: 'Impressum',
    891: 'Impressum',
    893: 'Index A-Z',
  };

  // Descrizioni SRF Teletext (Svizzera tedesca - SRF 1, zwei, info)
  final Map<int, String> srfDescriptions = {
    100: 'News',
    104: 'Inland',
    130: 'Ausland',
    150: 'Wirtschaft',
    165: 'Kultur',
    170: 'Vermischtes',
    180: 'Sport / News',
    200: 'Sport Index',
    201: 'Fussball Schweiz',
    230: 'Fussball Int. Ligen',
    260: 'Fussball CL & EL',
    280: 'Fussball EM',
    300: 'Eishockey Schweiz',
    320: 'Eishockey International',
    330: 'Tennis',
    350: 'F1+Moto',
    360: 'Rad',
    380: 'Ballsport',
    500: 'Meteo',
    501: 'Wetter',
    510: 'Spezialwetter',
    700: 'TV/Radio',
    702: 'TV Programm heute',
    712: 'TV Programm morgen',
    723: 'TV-Tipp',
    732: 'Jetzt auf allen Sendern',
    770: 'Untertitelung',
    780: 'Radio SRF Programm',
    790: 'RTR',
    800: 'Impressum',
    891: 'Impressum',
    893: 'Index A-Z',
  };

  // Descrizioni ORF1 Teletext (Austria - ORF1)
  final Map<int, String> orf1Descriptions = {
    // Topstory & Politik
    100: 'Seite 100',
    101: 'Topstory',
    106: 'ORF TV-Tipp',
    111: 'Schlagzeilen',
    112: 'Politik Österreich + EU',
    113: 'News Politik Österreich + EU',
    126: 'Politik International',
    127: 'News Politik International',
    135: 'Chronik',
    145: 'Leute',
    // Wirtschaft
    150: 'Wirtschaft',
    151: 'Wirtschaft News',
    155: 'Unternehmens-News',
    160: 'Börsen + Markt',
    161: 'Börse Wien',
    166: 'Börse Indizes',
    167: 'Börsen International',
    175: 'Devisen',
    176: 'Valuten',
    177: 'Gold + Silber',
    178: 'Insolvenzen',
    179: 'Arbeitslose / Inflation / BIP',
    // Kultur + Show
    190: 'Kultur + Show News',
    191: 'News Kultur',
    193: 'News Show',
    196: 'Kino',
    197: 'Tipp Kultur + Show',
    // Sport
    200: 'Sport Index',
    201: 'Sport Index',
    202: 'Sport Schlagzeilen',
    203: 'Sport vom Tag',
    210: 'Fußball',
    225: 'Tennis',
    230: 'Formel 1',
    232: 'Pferdesport / Rallye',
    233: 'Motorsport',
    234: 'Motorrad',
    235: 'Radsport',
    237: 'Wassersport',
    245: 'Kraftsport',
    251: 'Handball',
    252: 'Volleyball',
    253: 'Tischtennis',
    255: 'Golf',
    256: 'US-Ligen',
    259: 'Kurzmeldungen Sport',
    276: 'Eishockey',
    279: 'Behindertensport / ÖBSV aktiv',
    // Fernsehen
    300: 'TV-Programm',
    302: 'Zeit im Bild',
    303: 'Aktuell nach eins',
    304: 'Sport im TV',
    305: 'Konkret',
    306: 'Aktuell nach fünf',
    307: 'Studio 2',
    308: 'ORF TV-Tipp',
    311: 'ORF1 heute',
    317: '3sat heute/morgen',
    321: 'ORF2 heute',
    326: 'ZIB Magazin',
    327: 'ORF1 morgen',
    330: 'ORF2 morgen',
    333: 'Derzeit in ORF1/ORF2',
    334: 'Programmänderungen',
    335: 'TV-Programm Inhalte',
    350: 'TV-Programm Vorschau',
    356: 'Silvia kocht',
    357: 'Aufgetischt',
    358: 'bewusst gesund',
    359: 'Matinee am Sonntag',
    360: 'Okidoki',
    363: 'Guten Morgen Österreich',
    364: 'ORF III heute/morgen',
    370: 'ORF2 Europe',
    373: 'ORF SPORT+ heute/morgen',
    375: 'TV-Quoten (Teletest)',
    // Radios
    380: 'Radios',
    382: 'Ö1 Programm',
    383: 'Ö1 Inhalt heute',
    384: 'Hitradio Ö3',
    386: 'FM4',
    390: 'Radio Wien',
    391: 'Radio Niederösterreich',
    392: 'Radio Burgenland',
    393: 'Radio Oberösterreich',
    394: 'Radio Salzburg',
    395: 'Radio Tirol',
    396: 'Radio Vorarlberg',
    397: 'Radio Kärnten',
    398: 'Radio Steiermark',
    // Kultur + Show Termine
    400: 'Kultur + Show Termine',
    401: 'Konzerte Wien',
    403: 'Konzerte Bundesländer',
    407: 'Theater Wien',
    409: 'Theater Bundesländer',
    410: 'Bücher',
    411: 'Museen / Ausstellungen',
    413: 'RadioKulturhaus',
    417: 'Charts / Hitparade',
    // Help
    420: 'Help',
    421: 'Konsumenten-Informationen',
    425: 'AK-Tipps',
    // Motor
    430: 'Motor',
    431: 'Verkehrsmeldungen',
    432: 'Sperren + Baustellen',
    435: 'Billig tanken',
    // Multimedia
    460: 'Multimedia',
    461: 'Multimedia News',
    466: 'Frauen-Förderpreis',
    467: 'ORF TELETEXT in Web und als App',
    468: 'Webtipps',
    // Nachrichten leicht
    470: 'Nachrichten leicht (B1)',
    480: 'Nachrichten leichter (A2)',
    // Wetter
    600: 'Wetter',
    601: 'Messwerte Österreich',
    602: 'Wetter Bundesländer',
    611: '5-Tage-Vorschau',
    612: 'Bergwetter',
    613: 'Flugwetter',
    614: 'Gletscher',
    616: 'Wetter Nachbarländer',
    617: 'Wetter International',
    618: 'Donau-Pegel / Wasserstand',
    619: 'Wetter Statistik',
    620: 'Biowetter',
    621: 'Ozonwerte',
    622: 'Luftmesswerte',
    623: 'Strahlenmesswerte',
    624: 'Wetterwarnung',
    625: 'Segelwetter',
    // Gesundheit
    640: 'Gesundheit',
    641: 'Gesundheit aktuell',
    644: 'Hautvorsorge und UV-Index',
    645: 'Pollen-Information',
    646: 'Notrufe Gesundheit',
    648: 'Apotheken Wien/Bundesländer',
    657: 'Betreuung & Pflege',
    // Spenden
    680: 'Humanitäre Projekte / Licht ins Dunkel',
    681: 'Nachbar in Not',
    683: 'Team Österreich Tafel',
    685: 'Österreich hilft Österreich',
    // Bundesländer
    700: 'Bundesländer',
    701: 'Wien',
    702: 'Niederösterreich',
    703: 'Burgenland',
    704: 'Oberösterreich',
    705: 'Salzburg',
    706: 'Tirol',
    707: 'Vorarlberg',
    708: 'Kärnten',
    709: 'Steiermark',
    // Spiel + Sterne
    720: 'Spiel + Sterne',
    721: 'Lotto + Joker',
    722: 'Bingo',
    723: 'Euromillionen, Eurodreams',
    724: 'Klassenlotterie / Casinos Austria',
    725: 'Toto',
    726: 'Horoskop',
    733: 'Mondphasen',
    734: 'Kalendarium',
    735: 'Schach',
    736: 'Bridge',
    // Fußball 2
    750: 'Fußball 2',
    // Lesen statt Hören
    770: 'Lesen statt Hören',
    771: 'Untertitel Vorschau',
    772: 'Lesen statt Hören Beratung',
    773: 'Termine/Gehörlosensport',
    774: 'Gehörlosenseelsorge',
    776: 'Untertitel erstellt mit KI',
    777: 'Untertitel',
    778: 'Hörfilme, Hörsendungen',
    // Reisen
    800: 'Reisen',
    801: 'Reise-Tipps',
    805: 'Messen und Börsen',
    // Reiseinfo
    825: 'Reiseinfo',
    826: 'Fluglinien',
    827: 'Flughafen Wien Ankunft/Abflug',
    829: 'Flughafen Salzburg',
    830: 'Flughafen Graz',
    831: 'Flughafen Linz',
    832: 'Flughafen Innsbruck',
    833: 'Flughafen Klagenfurt',
    834: 'ÖBB Ankünfte/Abfahrten',
    839: 'Weltzeit',
    // Ihr ORF
    870: 'Ihr ORF',
    871: 'ORF-Service-Telefonnummern',
    872: 'ORF-Landesstudios',
    873: 'Abkürzungen / Kennzeichnung',
    874: 'ORF DIGITAL',
    876: 'ORF-Beitrag',
    877: 'Werben auf ORF.at',
    878: 'Werben im ORF TELETEXT',
    879: 'ORF-Backstage',
    880: 'ORF DIGITAL-HD',
    881: 'ORF nachlese',
    884: 'Offenlegung gem. § 25 MedienG',
    885: 'Impressum (Redaktion)',
    886: 'Testseite / Zeichenvorrat',
    // Index
    890: 'Index A-Z',
    899: 'Redaktion',
  };

  // Descrizioni ORF2 Teletext (Austria - ORF2)
  // ORF2 condivide la stessa struttura di ORF1
  final Map<int, String> orf2Descriptions = {
    // Topstory & Politik
    100: 'Seite 100',
    101: 'Topstory',
    106: 'ORF TV-Tipp',
    111: 'Schlagzeilen',
    112: 'Politik Österreich + EU',
    113: 'News Politik Österreich + EU',
    126: 'Politik International',
    127: 'News Politik International',
    135: 'Chronik',
    145: 'Leute',
    // Wirtschaft
    150: 'Wirtschaft',
    151: 'Wirtschaft News',
    155: 'Unternehmens-News',
    160: 'Börsen + Markt',
    161: 'Börse Wien',
    166: 'Börse Indizes',
    167: 'Börsen International',
    175: 'Devisen',
    176: 'Valuten',
    177: 'Gold + Silber',
    178: 'Insolvenzen',
    179: 'Arbeitslose / Inflation / BIP',
    // Kultur + Show
    190: 'Kultur + Show News',
    191: 'News Kultur',
    193: 'News Show',
    196: 'Kino',
    197: 'Tipp Kultur + Show',
    // Sport
    200: 'Sport Index',
    201: 'Sport Index',
    202: 'Sport Schlagzeilen',
    203: 'Sport vom Tag',
    210: 'Fußball',
    225: 'Tennis',
    230: 'Formel 1',
    232: 'Pferdesport / Rallye',
    233: 'Motorsport',
    234: 'Motorrad',
    235: 'Radsport',
    237: 'Wassersport',
    245: 'Kraftsport',
    251: 'Handball',
    252: 'Volleyball',
    253: 'Tischtennis',
    255: 'Golf',
    256: 'US-Ligen',
    259: 'Kurzmeldungen Sport',
    276: 'Eishockey',
    279: 'Behindertensport / ÖBSV aktiv',
    // Fernsehen
    300: 'TV-Programm',
    302: 'Zeit im Bild',
    303: 'Aktuell nach eins',
    304: 'Sport im TV',
    305: 'Konkret',
    306: 'Aktuell nach fünf',
    307: 'Studio 2',
    308: 'ORF TV-Tipp',
    311: 'ORF1 heute',
    317: '3sat heute/morgen',
    321: 'ORF2 heute',
    326: 'ZIB Magazin',
    327: 'ORF1 morgen',
    330: 'ORF2 morgen',
    333: 'Derzeit in ORF1/ORF2',
    334: 'Programmänderungen',
    335: 'TV-Programm Inhalte',
    350: 'TV-Programm Vorschau',
    356: 'Silvia kocht',
    357: 'Aufgetischt',
    358: 'bewusst gesund',
    359: 'Matinee am Sonntag',
    360: 'Okidoki',
    363: 'Guten Morgen Österreich',
    364: 'ORF III heute/morgen',
    370: 'ORF2 Europe',
    373: 'ORF SPORT+ heute/morgen',
    375: 'TV-Quoten (Teletest)',
    // Radios
    380: 'Radios',
    382: 'Ö1 Programm',
    383: 'Ö1 Inhalt heute',
    384: 'Hitradio Ö3',
    386: 'FM4',
    390: 'Radio Wien',
    391: 'Radio Niederösterreich',
    392: 'Radio Burgenland',
    393: 'Radio Oberösterreich',
    394: 'Radio Salzburg',
    395: 'Radio Tirol',
    396: 'Radio Vorarlberg',
    397: 'Radio Kärnten',
    398: 'Radio Steiermark',
    // Kultur + Show Termine
    400: 'Kultur + Show Termine',
    401: 'Konzerte Wien',
    403: 'Konzerte Bundesländer',
    407: 'Theater Wien',
    409: 'Theater Bundesländer',
    410: 'Bücher',
    411: 'Museen / Ausstellungen',
    413: 'RadioKulturhaus',
    417: 'Charts / Hitparade',
    // Help
    420: 'Help',
    421: 'Konsumenten-Informationen',
    425: 'AK-Tipps',
    // Motor
    430: 'Motor',
    431: 'Verkehrsmeldungen',
    432: 'Sperren + Baustellen',
    435: 'Billig tanken',
    // Multimedia
    460: 'Multimedia',
    461: 'Multimedia News',
    466: 'Frauen-Förderpreis',
    467: 'ORF TELETEXT in Web und als App',
    468: 'Webtipps',
    // Nachrichten leicht
    470: 'Nachrichten leicht (B1)',
    480: 'Nachrichten leichter (A2)',
    // Wetter
    600: 'Wetter',
    601: 'Messwerte Österreich',
    602: 'Wetter Bundesländer',
    611: '5-Tage-Vorschau',
    612: 'Bergwetter',
    613: 'Flugwetter',
    614: 'Gletscher',
    616: 'Wetter Nachbarländer',
    617: 'Wetter International',
    618: 'Donau-Pegel / Wasserstand',
    619: 'Wetter Statistik',
    620: 'Biowetter',
    621: 'Ozonwerte',
    622: 'Luftmesswerte',
    623: 'Strahlenmesswerte',
    624: 'Wetterwarnung',
    625: 'Segelwetter',
    // Gesundheit
    640: 'Gesundheit',
    641: 'Gesundheit aktuell',
    644: 'Hautvorsorge und UV-Index',
    645: 'Pollen-Information',
    646: 'Notrufe Gesundheit',
    648: 'Apotheken Wien/Bundesländer',
    657: 'Betreuung & Pflege',
    // Spenden
    680: 'Humanitäre Projekte / Licht ins Dunkel',
    681: 'Nachbar in Not',
    683: 'Team Österreich Tafel',
    685: 'Österreich hilft Österreich',
    // Bundesländer
    700: 'Bundesländer',
    701: 'Wien',
    702: 'Niederösterreich',
    703: 'Burgenland',
    704: 'Oberösterreich',
    705: 'Salzburg',
    706: 'Tirol',
    707: 'Vorarlberg',
    708: 'Kärnten',
    709: 'Steiermark',
    // Spiel + Sterne
    720: 'Spiel + Sterne',
    721: 'Lotto + Joker',
    722: 'Bingo',
    723: 'Euromillionen, Eurodreams',
    724: 'Klassenlotterie / Casinos Austria',
    725: 'Toto',
    726: 'Horoskop',
    733: 'Mondphasen',
    734: 'Kalendarium',
    735: 'Schach',
    736: 'Bridge',
    // Fußball 2
    750: 'Fußball 2',
    // Lesen statt Hören
    770: 'Lesen statt Hören',
    771: 'Untertitel Vorschau',
    772: 'Lesen statt Hören Beratung',
    773: 'Termine/Gehörlosensport',
    774: 'Gehörlosenseelsorge',
    776: 'Untertitel erstellt mit KI',
    777: 'Untertitel',
    778: 'Hörfilme, Hörsendungen',
    // Reisen
    800: 'Reisen',
    801: 'Reise-Tipps',
    805: 'Messen und Börsen',
    // Reiseinfo
    825: 'Reiseinfo',
    826: 'Fluglinien',
    827: 'Flughafen Wien Ankunft/Abflug',
    829: 'Flughafen Salzburg',
    830: 'Flughafen Graz',
    831: 'Flughafen Linz',
    832: 'Flughafen Innsbruck',
    833: 'Flughafen Klagenfurt',
    834: 'ÖBB Ankünfte/Abfahrten',
    839: 'Weltzeit',
    // Ihr ORF
    870: 'Ihr ORF',
    871: 'ORF-Service-Telefonnummern',
    872: 'ORF-Landesstudios',
    873: 'Abkürzungen / Kennzeichnung',
    874: 'ORF DIGITAL',
    876: 'ORF-Beitrag',
    877: 'Werben auf ORF.at',
    878: 'Werben im ORF TELETEXT',
    879: 'ORF-Backstage',
    880: 'ORF DIGITAL-HD',
    881: 'ORF nachlese',
    884: 'Offenlegung gem. § 25 MedienG',
    885: 'Impressum (Redaktion)',
    886: 'Testseite / Zeichenvorrat',
    // Index
    890: 'Index A-Z',
    899: 'Redaktion',
  };

  // Descrizioni ORF III Teletext (Austria - ORF III)
  final Map<int, String> orf3Descriptions = {
    100: 'Seite 100',
    // Fernsehen ORF III
    311: 'ORF III heute',
    327: 'ORF III morgen',
    333: 'Jetzt in ORF III',
    350: 'ORF III Programmvorschau',
    // Kultur + Show
    380: 'Kultur + Show News',
    400: 'Kultur + Show Termine',
    401: 'Konzerte Wien',
    403: 'Konzerte Bundesländer',
    407: 'Theater Wien',
    409: 'Theater Bundesländer',
    410: 'Bücher',
    411: 'Museen und Ausstellungen Wien',
    412: 'Museen und Ausstellungen Bundesländer',
    413: 'RadioKulturhaus',
    415: 'Wiener Festwochen',
    416: 'Donauinselfest',
    417: 'Charts Österreich',
    418: 'Charts International',
    405: 'Shows + Bands',
    // Nachrichten leicht
    470: 'Nachrichten leicht verständlich (B1)',
    480: 'Nachrichten leichter verständlich (A2)',
    // Wetter
    600: 'Wetter',
    601: 'Messwerte Österreich',
    602: 'Wetter Bundesländer',
    611: '5-Tage-Vorschau',
    613: 'Flugwetter',
    614: 'Gletscher',
    616: 'Wetter Nachbarländer',
    617: 'Wetter International',
    619: 'Wetter Statistik',
    624: 'Wetterwarnung',
    625: 'Segelwetter',
    // Spenden
    675: 'Corona-Regelungen und -Tests',
    680: 'Licht ins Dunkel / Spenden',
    681: 'Nachbar in Not',
    683: 'Team Österreich Tafeln',
    685: 'Österreich hilft Österreich',
    // Ihr ORF
    870: 'Ihr ORF',
    871: 'ORF-Service-Telefonnummern',
    872: 'ORF-Landesstudios',
    873: 'Kennzeichnung von Sendungen / Zeichenerklärung',
    874: 'ORF DIGITAL',
    876: 'ORF-Beitrags Service',
    880: 'ORF HD Empfang',
    884: 'Offenlegung',
    890: 'Index A-Z',
  };

  // Descrizioni ORF Sport+ Teletext (Austria - ORF Sport+)
  final Map<int, String> orfSportPlusDescriptions = {
    100: 'Seite 100',
    // Sport Übersicht
    200: 'Übersicht I',
    202: 'Schlagzeilen',
    // Fußball
    210: 'Fußball Bundesliga',
    213: 'Fußball 2.Liga',
    215: 'Fußball Deutschland',
    216: 'Fußball ENG / ITA',
    218: 'Fußball ESP / FRA',
    220: 'Fußball ÖFB-Kader',
    221: 'Fußball U17-WM',
    222: 'Fußball Meldungen',
    // Tennis
    225: 'Tennis',
    // Motorsport
    230: 'Formel 1',
    232: 'Motorsport',
    // Pferdesport
    244: 'Pferdesport',
    // Turnen
    248: 'Turnen',
    // Basketball
    250: 'Basketball',
    // Handball
    251: 'Handball',
    // Volleyball
    252: 'Volleyball',
    // Golf
    255: 'Golf',
    // US-Sport
    256: 'US-Sport',
    // Kurzmeldungen
    259: 'Kurzmeldungen',
    // Ski alpin
    263: 'Ski alpin',
    // Eishockey
    277: 'Eishockey',
    // ÖBSV
    279: 'ÖBSV aktiv',
    // Weitere Ergebnisse/Tabellen
    750: 'Weitere Ergebnisse/Tabellen',
    // Index
    890: 'Index A-Z',
  };

  // Descrizioni TVE Teletext (Spagna - TVE/RTVE - Televisión pública)
  final Map<int, String> tveDescriptions = {
    100: 'Índice',
    101: 'Primera Página',
    102: 'Nacional',
    120: 'Internacional',
    135: 'Noticias Deportes',
    200: 'Deportes Indice',
    201: 'Fútbol',
    210: 'Quiniela',
    220: 'Baloncesto',
    230: 'Motor',
    300: 'Servicios Indice',
    301: 'Servicios El Tiempo',
    400: 'Programas TVE',
    460: 'Sorteos',
    600: 'Tráfico',
    800: 'Gaceta Sordo',
  };

  // Descrizioni Antena 3 Teletext (Spagna - Atresmedia)
  final Map<int, String> antena3Descriptions = {
    100: 'Índice',
    101: 'Noticias',
    102: 'España',
    120: 'Economía',
    130: 'Deportes',
    140: 'Otros Deportes',
    150: 'Sociedad',
    160: 'Cultura',
    200: 'Marcador Fútbol',
    301: 'Loterías',
    330: 'El Tiempo',
    350: 'La Bolsa',
    800: 'Programación',
  };

  // Descrizioni La Sexta Teletext (Spagna - Atresmedia)
  final Map<int, String> lasextaDescriptions = {
   100: 'Índice',
    101: 'Noticias',
    102: 'España',
    120: 'Economía',
    130: 'Deportes',
    140: 'Otros Deportes',
    150: 'Sociedad',
    160: 'Cultura',
    200: 'Marcador Fútbol',
    301: 'Loterías',
    330: 'El Tiempo',
    350: 'La Bolsa',
    800: 'Programación',
  };

  // Descrizioni Portuguese Teletext (Portogallo - RTP)
  final Map<int, String> portugueseDescriptions = {
    100: 'Entrada',
    102: 'Índice Geral',
    103: 'TXT-O que é?',
    104: 'Contactos',
    105: 'Mira Técnica',
    112: 'PSP-Índice',
    117: 'Florestas',
    120: 'Notícias-Índice',
    121: 'Economia-Índice',
    125: 'Código Estrada',
    126: 'TDT',
    165: 'Solidariedade',
    188: 'Legendagens Hoje',
    189: 'Legendagens Amanhã',
    190: 'Legendagens Explicações',
    192: 'Audiodescrição',
    200: 'Nacional',
    215: 'Internacional',
    230: 'Economia',
    240: 'Bolsa Mundial',
    241: 'Ações PSI20',
    242: 'Bolsa-Variações',
    244: 'Câmbios',
    245: 'Desporto',
    260: 'Mundial 2010',
    275: 'Cultura',
    290: 'Jornais-Índice',
    295: 'D.República',
    300: 'Programação TV',
    301: 'RTP1 Hoje',
    302: 'RTP1 Amanhã',
    303: 'RTP1 Depois',
    304: 'Sinopses',
    335: 'RTP2 - Hoje',
    336: 'RTP2 - Amanhã',
    337: 'RTP2 - Depois',
    363: 'RTP Inf Hoje',
    364: 'RTP Inf Amanhã',
    366: 'RTPi A/O-Hoje',
    367: 'RTPi A/O-Amanhã',
    368: 'RTPi Amé-Hoje',
    369: 'RTPi Amé-Amanhã',
    370: 'RTPi Hoje',
    371: 'Satélites-Freq',
    372: 'RTPi Amanhã',
    373: 'RTPi Depois',
    375: 'RTP Afr-Hoje',
    376: 'RTP Afr-Amanhã',
    379: 'RTP Aço-Hoje',
    380: 'RTP Aço-Amanhã',
    383: 'RTP Mad-Hoje',
    384: 'RTP Mad-Amanhã',
    387: 'Sport TV Hoje',
    388: 'Sport TV Amanhã',
    391: 'RTP M Hoje',
    392: 'RTP M Amanhã',
    393: 'RTP M Depois',
    395: 'SIC Hoje',
    396: 'SIC Amanhã',
    398: 'TV1 Hoje',
    399: 'TV1 Amanhã',
    400: 'Desporto-índ',
    401: 'Nacional-Índice',
    402: 'Futebol Liga',
    409: 'Liga Honra',
    416: 'II Divisão A',
    419: 'II Divisão B',
    422: 'II Divisão C',
    425: 'II Divisão D',
    428: 'III Divisão A',
    431: 'III Divisão B',
    434: 'III Divisão C',
    437: 'III Divisão D',
    440: 'III Divisão E',
    443: 'III Divisão F',
    446: 'III D. Açores',
    449: 'Taça Portugal',
    450: 'Taça da Liga',
    451: 'Internacional',
    452: 'Liga Alemã',
    453: 'Liga Espanhola',
    454: 'Liga Francesa',
    455: 'Liga Inglesa',
    456: 'Liga Italiana',
    457: 'Liga Campeões',
    466: 'Modalidades',
    467: 'Futsal',
    468: 'Andebol Liga',
    469: 'Andebol Elite',
    470: 'Hóquei Patins',
    471: 'Basquetebol',
    472: 'Voleibol',
    473: 'Rugby',
    484: 'D.Motorizados',
    485: 'Fórmula 1',
    486: 'Motociclismo',
    487: 'Ralis C. Mundiais',
    488: 'Ralis C. Nacionais',
    490: 'Totolotarias',
    491: 'Totoloto',
    492: 'Joker',
    493: 'Loto2',
    495: 'Totobola',
    496: 'Totobola Extra',
    497: 'Lotarias Clássica',
    498: 'Lotarias Popular',
    499: 'Lotarias Extra',
    500: 'Utilidades',
    514: 'Culinária',
    517: 'Anedotas',
    518: 'Só para si',
    519: 'Horóscopos',
    553: 'Gripe Aviária',
    560: 'Gripe A',
    570: 'Marés',
    571: 'Marés Faro',
    572: 'Marés Cascais',
    573: 'Marés Leixões',
    574: 'B. Astronómico',
    575: 'Meteorologia',
    576: 'Continent-tempo',
    577: 'Fusos Horários',
    578: 'Madeira',
    579: 'Temperaturas',
    580: 'Açores-Tempo',
    582: 'Europa',
    586: 'Rádio-Frequên',
    587: 'Telef-Úteis',
    598: 'Calendário',
    690: 'Sismos-Ações',
    696: 'Euromilhões',
    800: 'Farmácias-índi',
  };

  // Descrizioni Dutch Teletext (Olanda - NOS)
  final Map<int, String> dutchDescriptions = {
    100: 'Voorpagina',
    101: 'Nieuws',
    102: 'Economie',
    103: 'Binnenland',
    104: 'Buitenland',
    105: 'Politiek',
    106: 'Cultuur',
    110: 'Tech',
    120: 'Koningshuis',
    128: 'Europa',
    129: 'Internationaal',
    200: 'Televisie',
    201: 'TV Gids NPO1',
    202: 'TV Gids NPO2',
    203: 'TV Gids NPO3',
    250: 'Radio',
    501: 'Financieel',
    502: 'Beurs',
    600: 'Sport',
    601: 'Sport Nieuws',
    633: 'Voetbal',
    649: 'Tennis',
    678: 'Schaatsen',
    700: 'Weer',
    701: 'Verkeer',
    800: 'Voetbal',
    801: 'Eredivisie',
    803: 'Internationaal Voetbal',
    888: 'Ondertiteling',
  };

  // Descrizioni Swedish Teletext (Svezia - SVT)
  final Map<int, String> swedishDescriptions = {
    100: 'Nyheter',
    101: 'Inrikes',
    104: 'Utrikes',
    150: 'Kultur',
    300: 'Sport',
    330: 'Resultatbörsen',
    376: 'Målservice',
    400: 'Väder',
    420: 'Snorapporten',
    500: 'Blandat',
    510: 'Böcker',
    570: 'Hundar',
    600: 'På TV',
    623: 'Mer om programmen',
    676: 'Radiohjälpen',
    700: 'Innehåll',
    711: 'Info om SVT Text'
  };

  // Descrizioni Finnish Teletext (Finlandia - YLE)
  final Map<int, String> finnishDescriptions = {
    100: 'Etusivu',
    101: 'Uutiset',
    102: 'Kotimaa',
    112: 'Vaaratiedotteet',
    130: 'Ulkomaat',
    160: 'Talous',
    175: 'Pörssisivut',
    190: 'News in English',
    196: 'Aakkosellinen hakemisto',
    200: 'Urheilu',
    201: 'Urheilu-uutiset',
    220: 'Palloilusarjat',
    298: 'Moottoriurheilu',
    300: 'Ohjelmat',
    301: 'Yle TV1',
    302: 'Yle TV2',
    303: 'MTV3',
    304: 'Nelonen',
    305: 'Yle Teema & Fem',
    306: 'Ava',
    307: 'Liv',
    308: 'Sub',
    309: 'JIM',
    310: 'Ylen kanavat huomenna',
    315: 'Ylen kanavat ylihuomenna',
    320: 'TV:ssä nyt',
    321: 'TV1 viikko',
    322: 'TV2 viikko',
    330: 'Tekstitysopas',
    337: 'Ääniteks titys',
    338: 'Tekstinpeitto',
    339: 'Yle Klassinen',
    340: 'Yle Radio1',
    341: 'YleX',
    342: 'Radio Suomi',
    344: 'Yöklassinen',
    348: 'Radio Suomi',
    349: 'Radiossa nyt',
    350: 'Ohjelmаopas',
    351: 'TV1',
    353: 'TV2',
    355: 'Yle Urheilu',
    356: 'Ajankohtaiset',
    359: 'Yle Teema & Fem',
    365: 'Nuntii Latini',
    371: 'Yle Areena',
    389: 'Yle Areena',
    400: 'Sää ja Liikenne',
    401: 'Säätiedotus',
    402: 'Maa-asemat',
    403: 'Merisää',
    404: 'Rannikkoasemat',
    405: '5 vrk:n sää',
    406: 'Päivän sää',
    407: '3 vrk:n sää',
    408: 'Ulkomaan sää',
    410: 'Tiesää, tietyöt',
    418: 'Siitepölyt/UV',
    420: 'Rinteet',
    424: 'Ilmanlaatu',
    425: 'Lennot: Hki',
    428: 'Lentosää',
    460: 'Ravit',
    470: 'Veikkaus',
    500: 'Alueuutiset, Tekniikka',
    501: 'Alueuutiset',
    550: 'Kuulosivut',
    575: 'Teksti-tv- ja digi-tv-tietoa',
    576: 'Teksti-TV-info',
    580: 'Testisivu',
    582: 'Lähetys-info',
    584: 'Yle-vero',
    588: 'Boxipäivitys',
    589: 'Digineuvonta',
    590: 'Radioamatöörit',
    591: 'DX-kuuntelijat',
    592: 'Ammunnat',
    599: 'Teksti-TV:n yhteystiedot',
    600: 'Suurtapahtumat',
    670: 'Euro jalkapallo',
    700: 'Text-TV på svenska',
    701: 'Huvudnyheter',
    702: 'Inrikes',
    710: 'Utrikes',
    715: 'Kultur och nöje',
    725: 'Huvudstadsreg.',
    730: 'Västnyland',
    735: 'Åboland',
    740: 'Österbotten',
    745: 'Östnyland',
    760: 'Väder',
    774: 'YleTeema&Fem',
    777: 'Radio Vega',
    778: 'Radio X3M',
    786: 'Textning',
    795: 'Nödhjälpssida',
    796: 'Hörselskadade',
    799: 'Index',
    800: 'Viikkomakasiini',
    801: 'Viikkomakasiinin hakemisto',
    802: 'Vapaa-aika',
    858: 'Eläketurva',
    860: 'Kansalaistaito',
    861: 'Kuluttaja',
    866: 'Vaaratiedote-info',
    867: 'Säteilyturva',
    868: 'Pelastuspalvelu',
    890: 'Kalenteri',
  };

  // Descrizioni Slovenian Teletext (Slovenia - RTV SLO)
  final Map<int, String> slovenianDescriptions = {
    101: 'Zadnja novica',
    102: 'Glavno kazalo',
    107: 'Test',
    108: 'Redakcija',
    109: 'Današnje novice',
    160: 'Vreme',
    165: 'Napoved za letalstvo',
    166: 'Agrometeorološko poročilo',
    167: 'Onesnaženost zraka',
    168: 'Stanje voda',
    169: 'Napoved za Primorje/Alpe',
    171: 'Ceste',
    172: 'Ceste',
    175: 'Cene goriv',
    178: 'Letalski promet',
    179: 'Letalski promet',
    184: 'Železniški promet',
    185: 'Železniški promet',
    186: 'Železniški promet',
    187: 'Železniški promet',
    188: 'Železniški promet',
    189: 'Železniški promet',
    190: 'Črna kronika',
    197: 'Kronika zadnjih 24 ur',
    198: 'Zaščita in reševanje',
    199: 'Osmrtnice',
    200: 'TV-programi',
    222: 'Pravkar na programu',
    224: 'Vsebine TV-oddaj',
    260: 'Radijski programi',
    264: 'Vabimo k poslušanju',
    265: 'Vabimo k poslušanju',
    266: 'Vabimo k poslušanju',
    270: 'RTV-informacije',
    271: 'Telefoni RTV Slovenija',
    272: 'Satelitske kartice',
    273: 'RTV-prispevek',
    291: 'Frekvence - TV/Radio',
    292: 'Frekvence - TV/Radio',
    300: 'Gospodarstvo',
    310: 'Tečajna lista Banke Slovenije',
    313: 'Borza / Ljubljanska borza',
    314: 'Ljubljanska borza',
    315: 'Ljubljanska borza',
    380: 'Temperature morja in jezer',
    400: 'Kultura',
    500: 'Šport',
    590: 'Rekreacija in športne zveze',
    597: 'Radioamaterji',
    599: 'Šah',
    600: 'Zabava',
    620: 'Kuharski recepti',
    626: 'Luna, sonce',
    627: 'Igre na srečo',
    629: 'Šale',
    640: 'SMS-storitve',
    761: 'Rdeči križ',
    762: 'Gluhi in naglušni',
    763: 'Slepi in slabovidni',
    770: 'Podnapisi za gluhe',
    780: 'Oglasi na TTX-u',
  };

  // Descrizioni Hungarian Teletext (Ungheria - MTVA)
  final Map<int, String> hungarianDescriptions = {
    100: 'Seite 100',
    101: 'Hírek röviden',
    102: 'Belföldi hírek',
    111: 'Feliratozás M1',
    130: 'Külföldi hírek',
    150: 'Gazdasági hírek',
    160: 'Kultúra',
    175: 'Időjárás',
    178: 'Orvos-meteorológia',
    179: 'Hőjelentés/Tengerek hőmérséklete',
    180: 'Pollenjelentés',
    181: 'Vízügyi hírek',
    182: 'Országos vízjelző szolgálat',
    185: 'Közlekedés',
    187: 'Útviszonyok',
    190: 'Repteri információ',
    191: 'Repteri információ',
    192: 'Repteri információ',
    193: 'Repteri információ',
    194: 'Repteri információ',
    195: 'Repteri információ / LRI',
    200: 'Sporthírek',
    222: 'Feliratozás M2',
    245: 'Totóeredmények',
    280: 'Sportcsatorna / M4 sport',
    300: 'Műsorok / Tévéműsorok',
    301: 'M1 műsora',
    315: 'M2 műsora',
    333: 'Duna',
    337: 'Automata feliratozó rendszer',
    350: 'DUNA TV műsorok / Tévéműsorok',
    365: 'DUNAWorld műsorok',
    385: 'Magazinok / Napi magazinok',
    397: 'Nemzetiségi magazinok',
    398: 'Kisebbségi műsorok / Műsoraink feliratozásáról',
    444: 'Feliratozás M4',
    450: 'M5 / Tévéműsorok',
    470: 'MTVA műsor-információk',
    473: 'Csukás meserádió / Meserádió',
    475: 'Szakcsí Rádió',
    476: 'Nemzeti Sportradio',
    478: 'M3 a neten',
    500: 'Gazdaság',
    502: 'Bankinfo',
    503: 'Devizaárfolyamok',
    530: 'Tőzsde',
    531: 'Részvények',
    536: 'Bux indexek',
    555: 'Duna World',
    580: 'Pénzügyi kisokos',
    702: 'Évfordulók',
    850: 'Segítő oldalak',
    852: 'Hallásserülteknek',
    853: 'Hallásserülteknek',
    861: 'A-Z Index',
    888: 'Feliratozás M5',
    898: 'Stáblista / Szerkesztőség',
  };

  // Descrizioni Icelandic Teletext (Islanda - RÚV)
  final Map<int, String> icelandicDescriptions = {
    100: 'Forsíða',
    101: 'Fréttir',
    102: 'Innlendar fréttir',
    103: 'Erlendar fréttir',
    104: 'Innlendar fréttir',
    105: 'Innlendar fréttir',
    120: 'Erlendar fréttir',
    121: 'Erlendar fréttir',
    140: 'Landsbyggðin',
    160: 'Veður',
    163: 'Landið',
    164: 'Næstu dagar',
    169: 'Weather forecast',
    181: 'Sjóveðurspá',
    200: 'Dagskrá',
    202: 'RÚV í kvöld',
    281: 'Lottó',
    300: 'Íþróttir',
    302: 'Íþróttafréttir',
    322: 'Laxveiðin',
    390: 'Boltaúrslit',
    400: 'Samgöngur',
    555: 'Efnisyfirlit A-Ö',
  };

  // Descrizioni RTL Text (Germania)
  final Map<int, String> rtlDescriptions = {
    100: 'Startseite',
    102: 'Nachrichten',
    110: 'Wetter',
    144: 'RTL aktuell',
    150: 'Guten Morgen Deutschland',
    180: 'Punkt 12',
    200: 'Sport',
    201: 'Fußball',
    202: 'Bundesliga',
    300: 'TV-Programm',
    301: 'RTL heute',
    302: 'RTL morgen',
    400: 'Ratgeber',
    500: 'Service',
    600: 'Unterhaltung',
    700: 'Börse',
  };
  
  // Descrizioni Croatian Teletext (Croazia - HRT)
  final Map<int, String> croatianDescriptions = {
    100: 'Sadržaj',
    110: 'Hrvatska',
    150: 'Svijet',
    180: 'Europska Unija',
    200: 'Gospodarstvo',
    250: 'Kultura',
    300: 'Program HTV-a',
    450: 'Vrijeme',
    500: 'Sport',
  };
  
  // Descrizioni Czech Teletext (Repubblica Ceca - ČT)
  final Map<int, String> czechDescriptions = {
    100: 'Obsah',
    101: 'Zprávy dne',
    110: 'Zprávy z domova',
    130: 'Zprávy ze světa',
    150: 'Regiony',
    160: 'Zajímavosti ze světa',
    170: 'Počasí',
    171: 'Počasí předpovědi',
    182: 'Počasí Slunce, Měsíc',
    185: 'Vodní stavy na řekách',
    187: 'Ovzduší',
    195: 'Počasí ve světě',
    198: 'Sníh v ČR',
    200: 'Sport',
    204: 'Fotbal',
    240: 'Fotbal',
    250: 'Lední hokej',
    280: 'Tenis',
    290: 'Motosport',
    300: 'Programy ČT',
    301: 'ČT dnešní program',
    331: 'ČT zítřejší program',
    360: 'ČT stránky pořadů',
    499: 'Sport na programu ČT sport',
    500: 'Finance',
    501: 'Burzy',
    503: 'Kurz koruny',
    550: 'RM-Systém',
    580: 'Oznámení',
    590: 'Kdo je kdo, co je co',
    600: 'Zájmy',
    601: 'Zdravý styl',
    610: 'Věda a technika',
    620: 'Recepty',
    625: 'Film v kinech',
    670: 'Poezie',
    680: 'Panorama',
    750: 'Tipsport',
    780: 'Sazka',
    800: 'Inzerce',
    801: 'Reklama',
    850: 'Stránky ČT',
    860: 'Televizní poplatek',
    862: 'Sledovanost programů',
    869: 'Vysílače DVB-T2',
    872: 'Digitalizace',
    880: 'Kariéra u ČT',
    895: 'Kontakty',
    896: 'Adresa teletextu',
    898: 'Technické stránky',
  };
  
  // Descrizioni Danish Teletext (Danimarca - DR)
  final Map<int, String> danishDescriptions = {
    100: 'Forside',
    105: 'DR: Nyt om DR',
    106: 'Indhold',
    109: 'Nyt seneste',
    110: 'Nyheder',
    150: 'Beredskabsmedd.',
    178: 'Fejl og Fakta',
    179: 'Meningsmålinger',
    194: 'Nyhed: seneste',
    198: 'Nyheder samt TV',
    200: 'Sport',
    257: 'Landbrugslot.',
    265: 'Oddset',
    284: 'Måljagt',
    291: 'Lotto',
    293: 'Vikinglotto',
    295: 'Keno',
    296: 'Klasselotteriet',
    300: 'TV+DR nu/næste',
    310: 'TV Nu på DR',
    313: 'Sport i TV',
    360: 'TV-Ugen',
    369: 'Dækhjelke',
    378: 'Serier DR1+DR2',
    379: 'Sport DR: Ugens',
    380: 'Film: Dagens',
    400: 'Vejret',
    437: 'Ur',
    438: 'Verdensur',
    439: 'Dagen i dag',
    470: 'Trafik',
    480: 'Fly',
    500: 'Film: Ugens',
    551: 'Valutakurser',
    570: 'Folketinget',
    576: 'Regeringen',
    578: 'EU2024:Landsres',
    579: 'Dks 15 medlem.',
    600: 'Radio',
    642: 'Dansktoppen',
    700: 'TV Publikum',
    724: 'Koncerthuset',
    727: 'Stillinger i DR',
    728: 'DR: Brugerkont.',
    730: 'Dave & hørehem.',
    740: 'DR: Information',
    741: 'Organdonorer',
    742: 'Alkolinjen',
    743: 'Røgfri-linien',
    744: 'Tekniske sider',
    745: 'Senderne',
    746: 'DR: Telefomnr.',
    756: 'Lotterier',
    758: 'Varelotteriet',
    760: 'Nyhed. regional',
    780: 'Drømmeholdet',
    888: 'Undertekster',
  };
  
  // Descrizioni BHRT Teletext (Bosnia ed Erzegovina - BHRT)
  final Map<int, String> bhrtDescriptions = {
    102: 'Sadržaj',
    109: 'Iz Zemlje',
    120: 'Iz Svijeta',
    140: 'Dnevna Štampa',
    152: 'Aktuелno',
    155: 'Na Današnji Dan',
    156: 'Tema Dana',
    159: 'Humani TTX',
    160: 'Kultura',
    161: 'Narodno Pozorište',
    162: 'Kamerni Teatar 55',
    163: 'Pozorište Mladih',
    164: 'SARTR',
    165: 'BNP',
    166: 'Kina',
    173: 'Galerije',
    174: 'Muzeji',
    186: 'Festivali',
    190: 'Religija',
    200: 'Sport',
    201: 'Nogomet',
    301: 'Program TV Današnji',
    306: 'Današnji Program FTV',
    307: 'Današnji Program RTRS',
    309: 'BH Radio 1 Današnji',
    310: 'Poned',
    319: 'Poned',
    320: 'Utorak',
    329: 'Utorak',
    330: 'Srijeda',
    339: 'Srijeda',
    340: 'Četvrtak',
    349: 'Četvrtak',
    350: 'Petak',
    359: 'Petak',
    360: 'Subota',
    369: 'Subota',
    370: 'Nedjelja',
    379: 'Nedjelja',
    380: 'Filmovi',
    381: 'Emisije',
    401: 'Za BiH',
    402: 'Za Sarajevo',
    403: 'Temperature Zraka u BiH',
    404: 'Temperature Zraka u Evropi',
    406: 'Stanje Na Putevima',
    410: 'Cjenovnik Marketinških Usluga',
    450: 'Servis',
    470: 'Klađionica BET-live',
    477: 'Važni Telefonski Brojevi',
    480: 'Dnevni Horoskop',
    493: 'Vodostaj',
    495: 'Međunarodni Aerodrom Odlasci',
    496: 'Dolasci',
    499: 'Kursna Lista',
    521: 'Doktor u Kući',
    522: 'Mali Savjeti',
    523: 'Dijete',
    525: 'Life Style',
    527: 'Zanimljivosti',
    528: 'Zrnca Mudrosti',
    529: 'Humor',
    530: 'Sanovnik',
    536: 'Ljepota i Zdravlje',
    540: 'Bontoni',
    545: 'Vaši Klinci',
    547: 'Za Djevojke',
    555: 'Horoskop Tjedni',
    588: 'Srebrenica',
    610: 'Mjesečni Horoskop',
    641: 'Kodeks za Štampu u BiH',
    644: 'Godišnji Horoskop',
    659: 'Klađionice Premier',
  };

  // Descrizioni RTVFBiH Teletext (Bosnia ed Erzegovina - Federalna TV)
  final Map<int, String> rtvfbihDescriptions = {
    102: 'Sadržaj',
    109: 'Iz Zemlje',
    120: 'Iz Svijeta',
    140: 'Dnevna Štampa',
    145: 'Šta Drugi Pišu',
    155: 'Na Današnji Dan',
    156: 'Tema Dana',
    160: 'Kultura',
    161: 'Narodno Pozorište',
    162: 'Kamerni Teatar 55',
    163: 'Pozorište Mladih',
    164: 'SARTR',
    166: 'Kina',
    173: 'Galerije',
    174: 'Muzeji',
    175: 'Kultura',
    186: 'Festivali',
    190: 'Religija',
    200: 'Sport',
    201: 'Nogomet',
    202: 'PL BiH',
    203: 'Kup BiH',
    204: 'Prva Liga FBiH',
    205: 'Prva Liga RS-a',
    206: 'A REP/BiH',
    207: 'U-21 REP/BiH',
    208: 'Njemačka Liga',
    209: 'Engleska Liga',
    210: 'Španska Liga',
    211: 'Italijanska Liga',
    212: 'Francuska Liga',
    213: 'Hrvatska Liga',
    214: 'Srbijanska Liga',
    215: 'Liga Prvaka',
    216: 'Evropska Liga',
    217: 'Konferencijska Liga',
    218: 'Euro 2024',
    220: 'Košarka',
    221: 'Liga BiH /M/',
    222: 'Liga BiH /Ž/',
    224: 'Reprezentacija (M)',
    225: 'Reprezentacija (Ž)',
    227: 'ABA Liga',
    229: 'Euroliga',
    230: 'Rukomet',
    231: 'Liga BiH /M/',
    232: 'Liga BiH /Ž/',
    233: 'Kup BiH',
    234: 'Euro 2024',
    235: 'Evropski Kupovi',
    240: 'Odbojka',
    262: 'Vijesti',
    301: 'Program TV Današnji',
    306: 'Današnji TV Program BHT1',
    307: 'Današnji TV Program RTRS',
    309: 'Radio FBiH Današnji',
    310: 'Ponedjeljak',
    319: 'Ponedjeljak',
    320: 'Utorak',
    329: 'Utorak',
    330: 'Srijeda',
    339: 'Srijeda',
    340: 'Četvrtak',
    349: 'Četvrtak',
    350: 'Petak',
    359: 'Petak',
    360: 'Subota',
    369: 'Subota',
    370: 'Nedjelja',
    379: 'Nedjelja',
    346: 'Predajnici i repetitori',
    380: 'Filmovi',
    382: 'Emisije',
    401: 'Za BiH',
    402: 'Za Sarajevo',
    403: 'Temperature Zraka u BiH',
    404: 'Temperature Zraka u Evropi',
    405: 'Snijeg',
    406: 'Stanje Na Putevima',
    407: 'Mjesečeve Mijene',
    408: 'Bioprognoza',
    409: 'Meteoalarm',
    410: 'Cjenovnik Marketinških Usluga',
    419: 'RTV Taksa',
    450: 'Servis',
    477: 'Telefonski Brojevi',
    480: 'Dnevni Horoskop',
    493: 'Vodostaj',
    495: 'Međunarodni Aerodrom Odlasci',
    496: 'Dolasci',
    499: 'Kursna Lista',
    501: 'Klađionice',
    511: 'Loto 6/39',
    512: 'Bingo',
    521: 'Doktor u Kući',
    522: 'Mali Savjeti',
    523: 'Dijete',
    525: 'Life Style',
    527: 'Zanimljivosti',
    528: 'Zrnca Mudrosti',
    529: 'Humor',
    530: 'Sanovnik',
    536: 'Ljepota i Zdravlje',
    537: 'Mali Savjeti',
    538: 'Cjeloživotno Učenje',
    540: 'Bonton',
    545: 'Vaši Klinci',
    547: 'Modne Igre Sezone',
    553: 'Ekologija',
    555: 'Sedmični Horoskop',
    569: 'Nevjerovatno, Zar Ne?!',
    610: 'Mjesečni Horoskop',
    644: 'Godišnji Horoskop',
  };
  
  // Descrizioni Ukrainian Teletext (Ucraina - Intertext)
  final Map<int, String> ukrainianDescriptions = {
    100: 'Головна',
    101: 'Новини',
    102: 'Україна',
    103: 'Світ',
    150: 'Економіка',
    160: 'Культура',
    200: 'Спорт',
    201: 'Футбол',
    300: 'Погода',
    400: 'Культура',
    500: 'ТВ-програма',
  };

  // Descrizioni SOM Teletextviewer (Germania/Austria/Svizzera - SAT.1, ProSieben, etc.)
  final Map<int, String> somDescriptions = {
    100: 'Inhalt',
    101: 'Schlagzeilen',
    111: 'News',
    120: 'Politik',
    130: 'Wirtschaft',
    140: 'Panorama',
    150: 'Ausland',
    170: 'Wetter',
    180: 'Verkehr',
    200: 'Sport',
    201: 'Fußball',
    202: 'Bundesliga',
    210: 'Weitere Sportarten',
    300: 'TV-Programm',
    301: 'SAT.1 heute',
    302: 'SAT.1 morgen',
    310: 'Spielfilm-Übersicht',
    320: 'TV-Tipps',
    350: 'Mediathek',
    395: 'JOYN',
    400: 'Service',
    450: 'Verbraucher',
    470: 'Ratgeber',
    500: 'Wetter',
    501: 'Wettervorhersage',
    510: 'Reisewetter',
    600: 'Lotto',
    650: 'Horoskop',
    700: 'Börse',
    800: 'Kontakt',
  };

  /// Ottiene le descrizioni in base al channelId
  Map<int, String> getDescriptionsForChannel({
    required String? channelId,
    required bool isRegional,
  }) {
    // Se channelId è null o inizia con 'rai', usa le descrizioni RAI
    if (channelId == null || channelId.startsWith('rai')) {
      return isRegional ? regionalDescriptions : nationalDescriptions;
    }
    
    // ARD Text
    if (channelId == 'ard_text') {
      return ardDescriptions;
    }
    
    // ZDF Text (Germania - Hauptprogramm)
    if (channelId == 'zdf_text') {
      return zdfDescriptions;
    }
    
    // ZDFinfo Text (Germania - Documentari)
    if (channelId == 'zdfinfo_text') {
      return zdfinfoDescriptions;
    }
    
    // ZDFneo Text (Germania - Entertainment)
    if (channelId == 'zdfneo_text') {
      return zdfneoDescriptions;
    }
    
    // 3sat Text (Germania/Austria/Svizzera - Cultura)
    if (channelId == '3sat_text') {
      return dreisatDescriptions;
    }
    
    // RSI Teletext (Svizzera italiana)
    if (channelId.startsWith('rsi_')) {
      return rsiDescriptions;
    }
    
    // RTS Teletext (Svizzera francese)
    if (channelId.startsWith('rts_')) {
      return rtsDescriptions;
    }
    
    // SRF Teletext (Svizzera tedesca)
    if (channelId.startsWith('srf_')) {
      return srfDescriptions;
    }
    
    // ORF1 Teletext (Austria)
    if (channelId == 'orf1') {
      return orf1Descriptions;
    }
    
    // ORF2 Teletext (Austria)
    if (channelId == 'orf2') {
      return orf2Descriptions;
    }
    
    // ORF III Teletext (Austria)
    if (channelId == 'orf3') {
      return orf3Descriptions;
    }
    
    // ORF Sport+ Teletext (Austria)
    if (channelId == 'orf_sport_plus') {
      return orfSportPlusDescriptions;
    }
    
    // TVE Teletext (Spagna - RTVE)
    if (channelId == 'tve') {
      return tveDescriptions;
    }
    
    // Antena 3 Teletext (Spagna - Atresmedia)
    if (channelId == 'antena3') {
      return antena3Descriptions;
    }
    
    // La Sexta Teletext (Spagna - Atresmedia)
    if (channelId == 'lasexta') {
      return lasextaDescriptions;
    }
    
    // Portuguese Teletext (Portogallo)
    if (channelId == 'rtp') {
      return portugueseDescriptions;
    }
    
    // Dutch Teletext (Olanda)
    if (channelId == 'nos_teletekst') {
      return dutchDescriptions;
    }
    
    // Swedish Teletext (Svezia)
    if (channelId == 'svt_text') {
      return swedishDescriptions;
    }
    
    // Finnish Teletext (Finlandia)
    if (channelId == 'yle_teksti_tv') {
      return finnishDescriptions;
    }
    
    // Slovenian Teletext (Slovenia)
    if (channelId == 'rtvslo_teletext') {
      return slovenianDescriptions;
    }
    
    // Hungarian Teletext (Ungheria)
    if (channelId == 'mtva_teletext') {
      return hungarianDescriptions;
    }
    
    // Icelandic Teletext (Islanda)
    if (channelId == 'ruv_textavarp') {
      return icelandicDescriptions;
    }
    
    // RTL Text
    if (channelId == 'rtl_text') {
      return rtlDescriptions;
    }
    
    // Croatian Teletext (HRT)
    if (channelId == 'hrt_teletekst') {
      return croatianDescriptions;
    }
    
    // Czech Teletext (ČT)
    if (channelId == 'ct_teletext') {
      return czechDescriptions;
    }
    
    // Danish Teletext (DR1 e DR2)
    if (channelId == 'dr1' || channelId == 'dr2') {
      return danishDescriptions;
    }
    
    // BHRT Teletext (Bosnia ed Erzegovina)
    if (channelId == 'bhrt') {
      return bhrtDescriptions;
    }
    
    // RTVFBiH Teletext (Bosnia ed Erzegovina - Federalna TV)
    if (channelId == 'rtvfbih') {
      return rtvfbihDescriptions;
    }
    
    // Ukrainian Teletext (Intertext)
    if (channelId == 'intertext') {
      return ukrainianDescriptions;
    }
    
    // SOM Teletextviewer (Germania/Austria/Svizzera)
    if (channelId.startsWith('som_')) {
      return somDescriptions;
    }
    
    // Default: RAI nazionale
    return nationalDescriptions;
  }

  // Ottiene la descrizione di una pagina (metodo legacy)
  @Deprecated('Use getDescriptionsForChannel instead')
  String getDescription(int pageNumber, {bool isRegional = false}) {
    final descriptions = isRegional ? regionalDescriptions : nationalDescriptions;
    return descriptions[pageNumber] ?? 'Pagina $pageNumber';
  }
} 